### ISSUE TITLE
Help explain deploy script

### ISSUE THREAD

**Issue by vanthao03596** [tuandm/laravue#106]
I see in Envoy.blade.php file have

echo 'Running deployment scripts'
cd {{ $new_release_dir }}
php artisan cache:clear
php artisan config:clear
php artisan view:clear
php artisan storage:link
php artisan migrate --force

and after

@task('update_symlinks')
echo 'Linking storage directory'
rm -rf {{ $new_release_dir }}/storage
ln -nfs {{ $app_dir }}/storage {{ $new_release_dir }}/storage

Can you explain why we run artisan config:clear, view:clear, ... on new release dir and then delete storage folder.

**Comment by tuandm** [comment]
@vanthao03596 
`config:clear`, `view:clear` to make sure there is no caching data (clear all caches).
`rm -rf {{ $new_release_dir }}/storage` and `ln -nfs {{ $app_dir }}/storage {{ $new_release_dir }}/storage` is to use storage from outside, so all releases will use same storage folder to avoid missing files creating in runtime. 
You can find more details on sample Envoy deploy script, ex: https://github.com/papertank/envoy-deploy

**Comment by vanthao03596** [comment]
@tuandm thanks for reply.
Anh ơi em chạy đến task clean_old_releases thì bị lỗi không biết có phải cài thêm gì ở vps để purge không anh nhỉ ?

**Comment by tuandm** [comment]
@vanthao03596 
Bạn coi trong [file](https://github.com/tuandm/laravue/blob/master/Envoy.blade.php) này nha:
```
@task('clean_old_releases')
    # This will list our releases by modification time and delete all but the 2 most recent.
    purging=$(ls -dt {{ $releases_dir }}/* | tail -n +3);
```
Cụ thể nó sẽ chạy lệnh `ls` để list các released folders. Ví dụ ở server mình đang deploy Laravue:
```
ls -dt /var/www/html/deploy/laravue/release/* | tail -n +3
```
Bạn thử chạy lệnh này trên VPS của bạn xem có ra lỗi gì không (chú ý thay cái `releases_dir` của bạn vào).

**Comment by vanthao03596** [comment]
Em gõ không thấy lỗi gì và cũng không hiển thị rồi anh ạ
![Screenshot from 2019-12-13 15-53-54](https://user-images.githubusercontent.com/34786441/70787248-db655900-1dc0-11ea-94a9-95cfcfbc39ec.png)

**Comment by tuandm** [comment]
@vanthao03596 
Folder hiện tại của bạn có 2 release, nếu bạn để `tail -n +3` thì nó sẽ giữ lại 2 release đó và không làm gì hết. Mình vẫn chưa hiểu bạn bị lỗi gì, có error gì không bạn?

User để deploy là user nào vậy bạn?

**Comment by vanthao03596** [comment]
Em run deploy bằng root lúc clean old release thì nó báo lỗi này 
![Screenshot from 2019-12-13 16-12-57](https://user-images.githubusercontent.com/34786441/70788461-8840d580-1dc3-11ea-8df3-617d852ad5c8.png)

**Comment by tuandm** [comment]
VPS bạn đang dùng xài OS nào vậy? (CentOS hay Ubuntu)?

**Comment by vanthao03596** [comment]
em dùng ubuntu 18.

**Comment by tuandm** [comment]
@vanthao03596 bạn cho mình xin nội dung file envoy của bạn được không ạ?

**Comment by vanthao03596** [comment]
@tuandm em sửa được rồi, cảm ơn anh. Em xin đóng issue.
