### ISSUE TITLE
fff

### ISSUE THREAD

**Issue by pramy-yang** [tuandm/laravue#107]
thanks open source

**Comment by puzzle9** [comment]
why
not why
why no why
because no why so no why

**Comment by pramy-yang** [comment]
> why
> not why
> why no why
> because no why so no why

I'm just a little confused  don't be so fierce.

**Comment by puzzle9** [comment]
> > why
> > not why
> > why no why
> > because no why so no why
> 
> I'm just a little confused don't be so fierce.

I'm sorry 
Just using `jwt` may be to comply with the `api` specification.
Using `session` in `api` doesn't feel so good
