### ISSUE TITLE
MarkdownEditor only renders

### ISSUE THREAD

**Issue by nckf** [tuandm/laravue#110]
I just need MarkdownEditor render section and I don't need to edit it
How do I change it？
Sorry, my english is not good.

**Comment by tuandm** [comment]
@nckf Laravue uses tui-editor which supports Viewer mode. 
The MarkdownEditor only load Editor mode, so you can not use Viewer mode with MarkdownEditor.
You can create MarkdownViewer component and load Viewer from tui-editor code:
```
import Viewer from 'tui-editor/dist/tui-editor-Viewer';
```
then initialize the Viewer with:

```
      this.editor = new Viewer({
        el: document.getElementById(this.id),
        ...this.editorOptions,
      });
```

**Comment by nckf** [comment]
![image](https://user-images.githubusercontent.com/29542062/70954949-1d84e800-20aa-11ea-9f43-8c7261426fd3.png)
![image](https://user-images.githubusercontent.com/29542062/70954990-3d1c1080-20aa-11ea-9016-6fc78a2eb448.png)
I seem to be missing some steps

**Comment by nckf** [comment]
![image](https://user-images.githubusercontent.com/29542062/70955055-72c0f980-20aa-11ea-9cd0-3406fd36d82b.png)
It looks something like this

**Comment by tuandm** [comment]
@nckf Seems you missed some options, please check this: https://github.com/nhn/tui.editor/blob/master/docs/getting-started.md#viewer

```
var Viewer = require('tui-editor/dist/tui-editor-Viewer');
...
var editor = new Viewer({
    el: document.querySelector('#viewerSection'),
    height: '500px',
    initialValue: '# content to be rendered'
});
...
```

**Comment by nckf** [comment]
> @nckf Seems you missed some options, please check this: https://github.com/nhn/tui.editor/blob/master/docs/getting-started.md#viewer
> 
> ```
> var Viewer = require('tui-editor/dist/tui-editor-Viewer');
> ...
> var editor = new Viewer({
>     el: document.querySelector('#viewerSection'),
>     height: '500px',
>     initialValue: '# content to be rendered'
> });
> ...
> ```

Thank you very much. It worked
