### ISSUE TITLE
Show all submenu instead of recently shown menu in tags view

### ISSUE THREAD

**Issue by Imtiaz17** [tuandm/laravue#111]
Let me explain my issue, In tags view I want all submenu when clicking one menu of a menu list ...like when I will click All users I want all submenus (all users, active users.....and so on) will appear in the tags view instead of recent shown menus... Is it possible?
[http://prntscr.com/qbixxi](http://prntscr.com/qbixxi)

**Comment by tuandm** [comment]
@Imtiaz17 As designed, the tabs view is to show all historical route, not submenus. I'm afraid that your request is not suitable with the project structure. The way to show history (from cached_views) is different to showing submenus (from route table).
