### ISSUE TITLE
Select 2 support

### ISSUE THREAD

**Issue by danniejpt** [tuandm/laravue#113]
Hello
How do you think about select2 support.
The form sections missing a lot of components

**Comment by tuandm** [comment]
@danniejpt Laravue has all UI components which [ElementUI](https://element.eleme.io/#/en-US/) offers, and Select is one of them. 
https://element.eleme.io/#/en-US/component/select
I think this is good enough. 

Adding select2 support will add a heavy jQuery, which we do not want.

Yes, the form page lacks lots of components. We will rebuild it soon :)
