### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by desarrollostello** [tuandm/laravue#114]
Everything was installed correctly, I can log in without problems. But when I want to perform some action that uses the database other than the login, I get that error. For example when I want to see the user's profile. The rest of the elements work perfect

Error: Request failed with status code 500    --> vendor.js line 406 > eval:16:15

```
module.exports = function createError(message, config, code, request, response) {
  var error = new Error(message);
  return enhanceError(error, config, code, request, response);
};
```

But that line is where it generates the error, not where it comes from. how strange that the login theoretically uses the DB and works well, therefore it does not seem to be a communication error

Thanks !!!

**Comment by drdee23** [comment]
I  can not even log In I’m having the same code 500 I can’t even login

**Comment by tuandm** [comment]
@desarrollostello Can you please provide more details on what you are getting? For example step by step or screenshots? I don't get the point here.

**Comment by tuandm** [comment]
@drdee23 Which steps you have done so far? What is the error message? Any screenshot?

**Comment by desarrollostello** [comment]
Thanks, I just fixed the problem. The problem was that I did not have the appropriate permissions for the **"storage"** folder

**Comment by drdee23** [comment]
i have done anything according to the instructions but still i cant login
it gives me a code 500 error so i cant get it

**Comment by tuandm** [comment]
@drdee23 For 500 error, you should check server log (of laravel) to see more detail. Or it may show on the browser console (Ex: Network tab - ajax call).
