### ISSUE TITLE
problem with dipendences on new fresh laravel installation

### ISSUE THREAD

**Issue by ftb** [tuandm/laravue#116]
installation failed, reverting ./composer.json to its original content.
Problem 1     
- Can only install one of: laravel/tinker[1.x-dev, v2.0.0].     - Can only install one of: laravel/tinker[v2.0.0, 1.x-dev].     
- Can only install one of: laravel/tinker[1.x-dev, v2.0.0].     - tuandm/laravue 0.7.3 requires laravel/tinker ^1.0 -> satisfiable by laravel/tinker[1.x-dev].    
- Installation request for tuandm/laravue ^0.7.3 -> satisfiable by tuandm/laravue[0.7.3].     
- Installation request for laravel/tinker (locked at v2.0.0, required as ^2.0) -> satisfiable by laravel/tinker[v2.0.0].

laravel 6.9.0

**Comment by tuandm** [comment]
@ftb Can you please provide step by step to reproduce? Latest release ([0.8.0](https://github.com/tuandm/laravue/releases/tag/0.8.0)) uses Laravel 6.9.0

**Comment by ftb** [comment]
forgive me... I'm a stupid idiot... all is fine. And thanks for the great work.
