### ISSUE TITLE
user cannot edit account

### ISSUE THREAD

**Issue by leonpug** [tuandm/laravue#121]
and not be able to change mail address, password...
Can only admin (or manager) do it?

**Comment by tuandm** [comment]
@leonpug Thanks for the report. User should be able to edit his account. We will fix.

**Comment by ngdangdat** [comment]
Hi @leonpug, user profile edit has been implemented in https://github.com/tuandm/laravue/pull/131 so that I close this issue.

Kindly check and tell us (by creating new issue) if there's any problem arise. Thanks for your report!

Regards,
Dat Nguyen
