### ISSUE TITLE
How to close tagsView dynamically

### ISSUE THREAD

**Issue by BechirAhmed** [tuandm/laravue#122]
Is it possible to close tagsView dynamically? if so How??

like when is submit form i want to close the view after success

**Comment by tuandm** [comment]
@BechirAhmed 
tagsView is built from `$store.state.tagsView.visitedViews`, you can close a tag by `this.$store.dispatch('tagsView/delView', view)` where view can be looked up from `visitedViews` by path. (`view` is a route instance).

You can check this file: https://github.com/tuandm/laravue/blob/master/resources/js/layout/components/TagsView/index.vue
```
    closeSelectedTag(view) {
      this.$store.dispatch('tagsView/delView', view).then(({ visitedViews }) => {
        if (this.isActive(view)) {
          this.toLastView(visitedViews);
        }
      });
    },
```

**Comment by BechirAhmed** [comment]
Great, Thanks @tuandm
