### ISSUE TITLE
Yarn Install --> error Couldnt't find the binary git

### ISSUE THREAD

**Issue by bwaw** [tuandm/laravue#124]
When i follow the Getting started instruction in Laravue, i got error when i run syntax YARN INSTALL.

The error is like this:

C:\xampp\htdocs\laravue2>yarn install
yarn install v1.21.1
[1/4] Resolving packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Is there any one ever meet error like that? 
Please help How to resolve it, (Fyi: i user windows 10 64 bit)

Thank you.

**Comment by tuandm** [comment]
@bwaw I think your issue could be similar to this one: https://github.com/tuandm/laravue/issues/88
