### ISSUE TITLE
Unclear usage of the token parameter in getInfo(token) of @/api/auth

### ISSUE THREAD

**Issue by ArnolFokam** [tuandm/laravue#125]
Hello guys, While exploring the codebase of laravue. I came across something strange but not really harmful for the project. I found a parameter that is unused IMHO. Thought I could report it if this was unintended and if not, Ask its utility because I can figure it out myself.

https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/api/auth.js#L1-L17

According to me, `token` parameter is never since `request` - **an instance of axios** always gets its token from the browser cookies using getToken().
https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/utils/request.js#L1-L26

https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/utils/auth.js#L1-L8

Therefore `function getInfo(token)` from [`@/api/auth.js`](https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/api/auth.js) ignores any value of passed to its parameter `token`. 
**Example**: It igonres the token goten from the store state passed by `getInfo({ commit, state })` from [`user.js`](https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/store/modules/user.js)
https://github.com/tuandm/laravue/blob/07ad034be0ea4abeba99bd44166d6d5c11aa9f31/resources/js/store/modules/user.js#L58-L73

So was this paramater left there for a future puspose or I have missunderstood the code?

**Comment by tuandm** [comment]
@ArnolFokam Token was removed when Laravue switched to Laravel Sanctum'. Regards.

Actually that token could be used if we use [Api Token Authentication](https://laravel.com/docs/7.x/sanctum#api-token-authentication).
