### ISSUE TITLE
Laravel Telescope

### ISSUE THREAD

**Issue by AugmentBLU** [tuandm/laravue#126]
Hi, great work on this project. 

I need to run Telescope and need to only allow access to specific users. There is a default Authorize Gate that ships with Telescope, however it's not working with Laravue. I can only assume it's the auth/api side. I

I can get the Telescope app to run fine, just not lock down who can access it. I don't mind if I have to manually specify accesses using the email array provided by Telescope and to view the application outwith the dashboard. I just need it to be accessible only to certain authenticated users. 

I have Telescope working with email specific access through the Gate on a vanilla Laravel install so it does work. 

Here's the default Gate
https://laravel.com/docs/5.7/telescope#dashboard-authorization

Would Passport potentially solve this? 

Thanks.

**Comment by tuandm** [comment]
Laravel Passport is now added to Laravue.
