### ISSUE TITLE
Using BrowserSync with yarn run watch

### ISSUE THREAD

**Issue by Quin452** [tuandm/laravue#127]
~~I'm using Laragon, and quintessentially, it is all I need for my dev work; works like a charm!~~

~~Now, I can use yarn run watch to keep track of changes being made, but I need to run php artisan server and use the localhost:port to see any changes.~~

~~Is there a way I can use Laragon's v-host (project-name.test) to reflect these changes, instead of localhost:port?~~

How can I use BrowserSync with Laravue/"yarn run watch"?

**Comment by tuandm** [comment]
@Quin452 https://doc.laravue.dev/guide/essentials/hot-reload.html
Please check here.

**Comment by Quin452** [comment]
Not to open it the issue again, just adding more info.

If you want to use browsersync for this, you need to load the site with the port number at the end (in my case "domain.local:3000") and it works :-)
