### ISSUE TITLE
Which file to write this code

### ISSUE THREAD

**Issue by dangquanghai** [tuandm/laravue#129]
Hi Man,
I follow your instruction https://doc.laravue.dev/vi/guide/development/work-with-resource.html 
to use resource but I don't know ưhich file to write this the code bellow ?

```
curl localhost:8000/api/categories
{
  "data": [] // Because there is no category in database
}

```
Thanks.

**Comment by martinnaughton** [comment]
in the instruction it says you need update the seeder: https://laravel.com/docs/master/seeding

If you have not used laravel before then you should learn about seeders. Check a tutorial on seeders in the link above. They go here. https://github.com/tuandm/laravue/tree/master/database/seeds

This more of basic laravel question. this should be resolved.

**Comment by tuandm** [comment]
@dangquanghai Sorry for this late response.
It's the CURL result to verify the cartegory API, you can use [postman](https://www.postman.com/) or [insomnia](https://insomnia.rest/) - they will give the same result. As @martinnaughton's comment, you have to add some categories using seeder to check.

**Comment by webtamizhan** [comment]
Hi @tuandm !

How can we testing the endpoint on POSTMAN using Laravel airlock(sanctum)? Because it is totally different from Bearer Token and Basic Authentication. Can you please elaborate if you have time please?

**Comment by LeonLoong** [comment]
> Hi @tuandm !
> 
> How can we testing the endpoint on POSTMAN using Laravel airlock(sanctum)? Because it is totally different from Bearer Token and Basic Authentication. Can you please elaborate if you have time please?
> 
> Or If you have any Pre-Request Script to test endpoint please share.

Hi @webtamizhan , I successfully did by following this tutorial.
[Laravel Sanctum (Airlock) with Postman](https://www.youtube.com/watch?v=QwjzjksfLMo)

Pre-Request Script is 
```
pm.sendRequest({
    url: 'http://127.0.0.1:8000/api/sanctum/csrf-cookie',
    method: 'GET'
}, function (error, response, { cookies }) {
    if (!error) {
        pm.environment.set('xsrf-token', cookies.get('XSRF-TOKEN'))
    }
})
```
If you want to know more, feel free to open a new issue.
The following are some references based on my project.
![001](https://user-images.githubusercontent.com/11975617/88013450-0716a180-cb4f-11ea-8033-445cd98c8721.JPG)
![002](https://user-images.githubusercontent.com/11975617/88013469-0c73ec00-cb4f-11ea-9ea1-31c9dd86bb97.JPG)

**Comment by webtamizhan** [comment]
> Hi @webtamizhan , I successfully did by following this tutorial.
> [Laravel Sanctum (Airlock) with Postman](https://www.youtube.com/watch?v=QwjzjksfLMo)
> 
> Pre-Request Script is
> 
> ```
> pm.sendRequest({
>     url: 'http://127.0.0.1:8000/api/sanctum/csrf-cookie',
>     method: 'GET'
> }, function (error, response, { cookies }) {
>     if (!error) {
>         pm.environment.set('xsrf-token', cookies.get('XSRF-TOKEN'))
>     }
> })
> ```
> 
> If you want to know more, feel free to open a new issue.
> The following are some references based on my project.
> ![001](https://user-images.githubusercontent.com/11975617/88013450-0716a180-cb4f-11ea-8033-445cd98c8721.JPG)
> ![002](https://user-images.githubusercontent.com/11975617/88013469-0c73ec00-cb4f-11ea-9ea1-31c9dd86bb97.JPG)

Thanks buddy, it works well!
