### ISSUE TITLE
此文件在ie11下无法显示，空白一片，还报的是vendor.js的错误，实在无从下手

### ISSUE THREAD

**Issue by fenglijunnb** [tuandm/laravue#130]
@nguyenquangtin @tuandm @JBtje @fawzanm @XaoZlo 
![image](https://user-images.githubusercontent.com/48191768/75016279-95fe8f80-54c5-11ea-8484-59cf5110ef0f.png)

**Comment by ankitce** [comment]
I am having the same issue. I tried with different babel plugins and configuration with no success. 
Any update on this?

**Comment by tuandm** [comment]
@ankitce Thanks for your code. We have applied it on [the latest version](https://github.com/tuandm/laravue/tree/0.12.0). 

Regards
