### ISSUE TITLE
Unable to migrate database after change to Laravel passport

### ISSUE THREAD

**Issue by Kuzuto** [tuandm/laravue#133]
With a fresh project, the php artisan migrate is not possible. Error in the Role table:

Migrating: 2019_04_20_130706_setup_role_permissions

   Spatie\Permission\Exceptions\RoleDoesNotExist  : There is no role named `admin`.

  at /home/vagrant/code/laravue/vendor/spatie/laravel-permission/src/Exceptions/RoleDoesNotExist.php:11
     7| class RoleDoesNotExist extends InvalidArgumentException
     8| {
     9|     public static function named(string $roleName)
    10|     {
  > 11|         return new static("There is no role named `{$roleName}`.");
    12|     }
    13| 
    14|     public static function withId(int $roleId)
    15|     {

  Exception trace:

  1   Spatie\Permission\Exceptions\RoleDoesNotExist::named()
      /home/vagrant/code/laravue/vendor/spatie/laravel-permission/src/Models/Role.php:87

  2   Spatie\Permission\Models\Role::findByName()
      /home/vagrant/code/laravue/database/migrations/2019_04_20_130706_setup_role_permissions.php:22

**Comment by Kuzuto** [comment]
I found out that because config/auth.php is now changed to 'web' as default, it's looking in the roles table after name->admin with guard_name->web , that do not exist. Only 'api' is created.

Don't know what the correct way is to fix this.

**Comment by tuandm** [comment]
@Kuzuto Thanks for your report. We'll look into this issue ASAP.

**Comment by tuandm** [comment]
@Kuzuto Please checkout the newest code and run migration again.
