### ISSUE TITLE
UnauthorizedException after change to Laravel Passport

### ISSUE THREAD

**Issue by Kuzuto** [tuandm/laravue#135]
From a fresh project, it's not possible to access menu:

- Users
- Role Permissions

The response from the api call is :
"message": "User is not logged in.",
"exception": "Spatie\\Permission\\Exceptions\\UnauthorizedException"

**EDIT:**
Fixed it by wrapping 
`Route::group(['middleware' => 'auth:api'], function () {
...
}`
around the users routes in the api.php

**Comment by tuandm** [comment]
@Kuzuto Thanks for the report. Fixed as your suggestion.
