### ISSUE TITLE
Laravel airlock

### ISSUE THREAD

**Issue by tuandm** [tuandm/laravue#139]
Regarding the purpose and usages of Laravue, we are considering moving to [Laravel Airlock](https://github.com/laravel/airlock) instead of Laravel Passport. Current work with Laravel Passport will be archived in new branch and keep syncing with latest code as much as possible.

**Comment by AugmentBLU** [comment]
Looks like it might be a better fit for an SPA. Any ETA for integrating with Laravue?

**Comment by tuandm** [comment]
#150
