### ISSUE TITLE
Can't run `docker-compose up -d`

### ISSUE THREAD

**Issue by WebExp0528** [tuandm/laravue#145]
![image](https://user-images.githubusercontent.com/46267354/77125517-3da6a900-6a03-11ea-8de0-ff54e76b6311.png)
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: spatie/laravel-permission
Package manifest generated successfully.
Removing intermediate container 77edaa7784e8
 ---> 5d1b83ec5f0e
Step 13/14 : RUN php artisan passport:install
 ---> Running in f88aa287b1de
Encryption keys generated successfully.

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] No such file or directory (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, Laravel Personal Access Client, dCLlFZF1OMOzMjKULOA8jbk5LIdkKMSqCzrbK2yi, http://localhost, 1, 0, 0, 2020-03-19 23:18:45, 2020-03-19 23:18:45))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

      +48 vendor frames 
  49  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
ERROR: Service 'laravel' failed to build: The command '/bin/sh -c php artisan passport:install' returned a non-zero code: 1

**Comment by algers** [comment]
Try updating DB_HOST environment variable from 'localhost' to '127.0.0.1' or using postgres instead of mysql

**Comment by WebExp0528** [comment]
Also, I am getting the same error.

**Comment by WebExp0528** [comment]
I am using docker latest version.

**Comment by tuandm** [comment]
@WebExp0528 It's reported here: https://github.com/tuandm/laravue/issues/142. We are fixing it.
