### ISSUE TITLE
安装后报错

### ISSUE THREAD

**Issue by 957651480** [tuandm/laravue#154]
php 版本7.3
第一个报错

Warning: array_shift() expects parameter 1 to be array, null given in I:\phpwrorkspace\laravue\vendor\symfony\console\Input\ArgvInput.php on line 53
--

1 | 0.0001 | 397432 | {main}( ) | ...\server.php:0
2 | 0.0003 | 397784 | require_once( 'I:\phpwrorkspace\laravue\public\index.php' ) | ...\server.php:21
3 | 0.0090 | 855000 | App\Http\Kernel->handle( object(Illuminate\Http\Request)[50] ) | ...\index.php:55
4 | 0.0090 | 855000 | App\Http\Kernel->sendRequestThroughRouter( object(Illuminate\Http\Request)[50] ) | ...\Kernel.php:109
5 | 0.0091 | 856632 | App\Http\Kernel->bootstrap( ) | ...\Kernel.php:135
6 | 0.0091 | 856632 | Illuminate\Foundation\Application->bootstrapWith( array(6) ) | ...\Kernel.php:151
7 | 0.0092 | 857464 | Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables->bootstrap( object(Illuminate\Foundation\Application)[2] ) | ...\Application.php:228
8 | 0.0093 | 857464 | Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables->checkForSpecificEnvironmentFile( object(Illuminate\Foundation\Application)[2] ) | ...\LoadEnvironmentVariables.php:26
9 | 0.0095 | 864264 | Symfony\Component\Console\Input\ArgvInput->__construct( ???, ??? ) | ...\LoadEnvironmentVariables.php:43
10 | 0.0095 | 864288 | array_shift ( null ) | ...\ArgvInput.php:53

第二个报错
Warning: Invalid argument supplied for foreach() in I:\phpwrorkspace\laravue\vendor\symfony\console\Input\ArgvInput.php on line 279
Call Stack
#	Time	Memory	Function	Location
1	0.0001	397432	{main}( )	...\server.php:0
2	0.0003	397784	require_once( 'I:\phpwrorkspace\laravue\public\index.php' )	...\server.php:21
3	0.0090	855000	App\Http\Kernel->handle( object(Illuminate\Http\Request)[50] )	...\index.php:55
4	0.0090	855000	App\Http\Kernel->sendRequestThroughRouter( object(Illuminate\Http\Request)[50] )	...\Kernel.php:109
5	0.0091	856632	App\Http\Kernel->bootstrap( )	...\Kernel.php:135
6	0.0091	856632	Illuminate\Foundation\Application->bootstrapWith( array(6) )	...\Kernel.php:151
7	0.0092	857464	Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables->bootstrap( object(Illuminate\Foundation\Application)[2] )	...\Application.php:228
8	0.0093	857464	Illuminate\Foundation\Bootstrap\LoadEnvironmentVariables->checkForSpecificEnvironmentFile( object(Illuminate\Foundation\Application)[2] )	...\LoadEnvironmentVariables.php:26
9	0.0180	876656	Symfony\Component\Console\Input\ArgvInput->hasParameterOption( string(5), ??? )	...\LoadEnvironmentVariables.php:43

**Comment by tuandm** [comment]
Can you please provide more steps to reproduce? I guess this issue is not related to Laravue framework.

**Comment by 957651480** [comment]
使用php artisan  serve 运行报错，web服务器运行没问题------------------ 原始邮件 ------------------
发件人: "Tuan Duong"<notifications@github.com>
发送时间: 2020年4月4日(星期六) 下午4:50
收件人: "tuandm/laravue"<laravue@noreply.github.com>;
抄送: "摇滚哈哈狗"<957651480@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tuandm/laravue] 安装后报错 (#154)




 
Can you please provide more steps to reproduce? I guess this issue is not related to Laravue framework.
 
&mdash;
