### ISSUE TITLE
Big size Vendor.js

### ISSUE THREAD

**Issue by Imtiaz17** [tuandm/laravue#155]
Hi, I want to remove <script src="{{ mix('js/vendor.js') }}"></script> from my blade file but if i remove it project won't work. While in run of development moode the vendor.js size is quite bigger 10mb+ .Why is this necessary to this project?? As all my js code is compile in app.js.How to get rid of the vendor .js or compress it?

**Comment by tuandm** [comment]
@Imtiaz17 

Vendor.js can not be removed because it contains on vendor code, please check [vendor extraction](https://laravel.com/docs/7.x/mix#vendor-extraction)

For the big size question, please check [this](https://github.com/tuandm/laravue/issues/62)
