### ISSUE TITLE
vue-element-admin version

### ISSUE THREAD

**Issue by sabatale** [tuandm/laravue#156]
This may have been asked already but is there any update strategy for whenever the vue-element-admin frontend is being updated? From what I see the frontend is being hardcoded in the repo - what version has been used?

I've faced many bugs I hadn't encountered in vue-element-admin itself. Are there guidelines on how to update it "easily"? or would the recommendation be to adjust the delta manually for every file

Thanks for your work!

**Comment by tuandm** [comment]
@sabatale There is no good strategy at this time. We are doing it manually with some comparing tools. And yes, Laravue should keep updating with vue-element-admin. We will try to do this. Thanks.
