### ISSUE TITLE
Can I run project without php artisan

### ISSUE THREAD

**Issue by binh27112004** [tuandm/laravue#163]
Can I run project without php artisan.
And how can i deploy my project to Hostinger :(

**Comment by tuandm** [comment]
@binh27112004 Yes you can, Laravue is Laravel, you can setup vhost and run normally.

**Comment by binh27112004** [comment]
@tuandm but I can't setup vhost in hostinger's Host

**Comment by tuandm** [comment]
@binh27112004 Does Hostinger support Laravel? I think yes: https://www.hostinger.com/laravel-hosting
Sorry I can't help you here, the issue is not related to Laravue framework.
