### ISSUE TITLE
blank screen 

### ISSUE THREAD

**Issue by sirjp1** [tuandm/laravue#166]
someone, please help me. just finished uploading my application but it is showing a blank screen. my link to the codes is https://github.com/sirjp1/ecommerce. please i need help urgently

**Comment by tuandm** [comment]
Can I get more details? How is your project related to Laravue? What're steps you have done so far? Any error message or screenshot? Have you checked chrome console to see any message there?

**Comment by sirjp1** [comment]
Used php. On chrome it showed http error 500 . my sever is apache wamp  

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 16, 2020 at 11:58 AM, Tuan Duong<notifications@github.com> wrote:   


Can I get more details? How is your project related to Laravue? What're steps you have done so far? Any error message or screenshot? Have you checked chrome console to see any message there?

**Comment by tuandm** [comment]
If the error code is 500, there are some errors from the server side, please check laravel/apache log for more detail.

**Comment by sirjp1** [comment]
Where do i go to check the log on apache and what else can be done? You can also check my codes to see if i got anything wrong anywhere. I have been having sleepless nights on it

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 16, 2020 at 1:21 PM, Tuan Duong<notifications@github.com> wrote:   


If the error code is 500, there are some errors from the server side, please check laravel/apache log for more detail.

**Comment by tuandm** [comment]
@sirjp1 You gave me the link which is not related to Laravue project. I don't think there is anything I can help here.

**Comment by balanso** [comment]
> Where do i go to check the log on apache and what else can be done? You can also check my codes to see if i got anything wrong anywhere. I have been having sleepless nights on it Sent from Yahoo Mail on Android On Thu, Apr 16, 2020 at 1:21 PM, Tuan Duong<notifications@github.com> wrote: If the error code is 500, there are some errors from the server side, please check laravel/apache log for more detail. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

add .htaccess to root of your project
with contents:
RewriteEngine on
RewriteCond %{REQUEST_URI} !^public
RewriteRule ^(.*)$ public/$1 [L]

**Comment by arslan-butt** [comment]
Most probably your assets not generating. eg:

under the public folder
`css/app.css`
`js/app.js  js/manifest.js  js/vendor.js`

Have you tried this command?
`$ npm run dev`
