### ISSUE TITLE
Auto reloading error

### ISSUE THREAD

**Issue by Rastarex** [tuandm/laravue#167]
Hi,
i was just starting to play with laravue in xampp, but when i try to initiate auto reloading with the commands "npm run hot" and "php artisan serve" i get these errors on the console

> GET http://localhost:8080//css/app.css net::ERR_CONNECTION_REFUSED
> localhost/:34 GET http://localhost:8080//js/vendor.js net::ERR_CONNECTION_REFUSED
> localhost/:35 GET http://localhost:8080//js/manifest.js net::ERR_CONNECTION_REFUSED
> localhost/:36 GET http://localhost:8080//js/app.js net::ERR_CONNECTION_REFUSED

I believed that it was probably the same problem that is explained on the docs, but can't solve it with the solution presented.

  ```
mix.options({
    hmrOptions: {
      host: {YOUR_VHOST_NAME},
      port: 8080,
    },
  });
```
(webpack.mix.js)
what should be the correct vhost name? localhost right?

**Comment by hungnm1518** [comment]
if you use vhost in xampp, add this into mix.webpackConfig

`      devServer: {
        headers: {
          'Access-Control-Allow-Origin': '*',
        },
        contentBase: path.join(__dirname, 'public'),
        compress: true,
        hot: true,
        inline: true,
      },`

**Comment by tuandm** [comment]
@Rastarex 
If you are using `php artisan serve`, no need to config hrmOptions. Default setting is working fine to me. 

Below is my test from fresh installation (latest code on master)
`npm run hot` result:
```
➜  npm run hot
> laravue@0.11.0 hot [src]
> cross-env NODE_ENV=development BABEL_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from http://localhost:8080/
ℹ ｢wds｣: Content not from webpack is served from [src]/public
ℹ ｢wds｣: 404s will fallback to /index.html
```
`php artisan serve` result:
```
➜  php artisan serve
Laravel development server started: http://127.0.0.1:8000
```

And browser:

![image](https://user-images.githubusercontent.com/490446/80058312-27848f00-8553-11ea-8127-9c9dea336ef5.png)

**Comment by CloudyCity** [comment]
@tuandm 
I have same problem. I didn't change any code after `composer create-project`.

`run watch` with Browsersync can work but `run hot` can't.

Here is my flow.
```
$ composer create-project tuandm/laravue
$ cd laravue
$ npm i
```
```
$ npm run hot

> laravue@0.13.1 hot /Users/lyc/Sites/laravue
> cross-env NODE_ENV=development BABEL_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js




 DONE  Compiled successfully in 19322ms
```

```
$ php artisan serve
Laravel development server started: http://127.0.0.1:8000
```

![image](https://user-images.githubusercontent.com/17662451/100491478-cf53e200-315e-11eb-9c16-b474a8137a8a.png)

Folder `/public/js/` is empty after `run hot`, is it normal?
