### ISSUE TITLE
Updating existing laravue starter project

### ISSUE THREAD

**Issue by jigzstar** [tuandm/laravue#173]
What is the best way to update an existing starter project? I started a project about a month ago,
using ``` composer create-project tuandm/laravue ``` and realized there were some core changes to the Laravue package, that I want to pull down to my installation. What's the best way to update?

**Comment by joakim-emagine** [comment]
I'm guessing, making a fork() of this repo, and pulling latest fixes could work?

**Comment by jigzstar** [comment]
I'm guessing, making a fork() of this repo, and pulling latest fixes could work?

**Comment by tuandm** [comment]
@jigzstar Unfortunately, updating is not ready at this time. We are still working on providing more useful features on Laravue components. For now, yes, you can fork this repo and check the latest code - then compare with your existing ones. Please be careful when merging.

**Comment by joakim-emagine** [comment]
Thanks! No worries. Great project btw the way!

**Comment by jigzstar** [comment]
Thanks, no worries. Great project BTW!
