### ISSUE TITLE
Unable to browse documentation website (Your connection is not private)

### ISSUE THREAD

**Issue by LeonLoong** [tuandm/laravue#184]
When I try to browse [https://doc.laravue.dev](https://doc.laravue.dev) ,  <Your connection is not private, NET::ERR_CERT_DATE_INVALID> error is come out.
![Capture](https://user-images.githubusercontent.com/11975617/83314629-f41dda00-a24d-11ea-8b52-095f155f11ee.JPG)
Btw, thanks for this project, it helped me a lot.

**Comment by tuandm** [comment]
@LeonLoong Thanks for the report. It's fixed.
