### ISSUE TITLE
Verification failed, please Login again.

### ISSUE THREAD

**Issue by jobinpankajan** [tuandm/laravue#185]
Getting login error "Verification failed, please Login again." could you please give me a solution

**Comment by Kuzuto** [comment]
Did you seed the database?

**Comment by jobinpankajan** [comment]
Yes db connection is working, but getting login error 401

**Comment by Kuzuto** [comment]
Yes, but did you seed the database with php artisan db:seed ?

**Comment by jobinpankajan** [comment]
all these step followed : 

php artisan migrate --seed

npm install

npm run dev # or npm run watch

**Comment by jobinpankajan** [comment]
vue-router.esm.js?8c4f:2089 - Uncaught (in promise) undefined

**Comment by Kuzuto** [comment]
Check the network debug to see what the respond is from server. Could be some missing Laravel permissions.

**Comment by jobinpankajan** [comment]
got this - {"error":"Unauthorized"}

**Comment by thaild** [comment]
I got same error as @jobinpankajan

**Comment by jobinpankajan** [comment]
Any solution ?

**Comment by Kuzuto** [comment]
Seems strange.. I just did a clean installation and followed the guide :
composer create-project tuandm/laravue
cd laravue
php artisan migrate --seed
npm install
npm run dev

It all works fine for me out of the box.. Login without problems.
Maybe you can try to run **composer update**

**Comment by thaild** [comment]
Yes, It's work for now. 
I tried again following the instructions above, instead of using the `master` branch

**Comment by tuandm** [comment]
@thaild For the first installation, you should go with the [released versions](https://github.com/tuandm/laravue/releases) (which are from `composer create-project tuandm/laravue`). `master` branch is maintained to be stable as much as possible but it's not.

**Comment by tuandm** [comment]
@jobinpankajan Can you please provide more details? Have you checked the DB to see if the user exists? Can you please create new fresh DB and try `php artisan migrate --seed` again to be sure?

**Comment by LeftPinkie** [comment]
I got a similar error, not on `login` but 401 Unauthorized on `user` after `login`. As Tuân (@tuandm) suggested, use a release version.  I was successful when I used release version 0.12.0.  Here is the syntax for `composer`:
```
composer create-project --prefer-dist tuandm/laravue=0.12.0 laravue
```

By the way, I do not know if this contributed to the fix but I also ran `npm audit fix --force` after `npm install` to force fix a high vulnerability.

**Comment by sid3r** [comment]
Git the same issue here, Can't see where is the issue exactly :/ . It's a bit strange since i didn't change anything so i can go back add to that I did some cleaning of the code and made a coupe of adjustements and modules so it's pain in the a*** to restart from scratch.  I did track changes using git but even going back some commits nothing seems to correct the issue. any idea where the bug comes from?

**Comment by sid3r** [comment]
here's some infos, it seems that the login request succeeded.

<img width="805" alt="Capture d’écran 2020-07-03 à 20 26 16" src="https://user-images.githubusercontent.com/4179728/86493993-8c3a4200-bd6b-11ea-9cf4-216fc7e694f0.png">

but the get user didn't.

<img width="805" alt="Capture d’écran 2020-07-03 à 20 26 26" src="https://user-images.githubusercontent.com/4179728/86493998-90665f80-bd6b-11ea-81ee-897f0170cb2d.png">

**Comment by LeftPinkie** [comment]
> here's some infos, it seems that the login request succeeded.
> 
> <img alt="Capture d’écran 2020-07-03 à 20 26 16" width="805" src="https://user-images.githubusercontent.com/4179728/86493993-8c3a4200-bd6b-11ea-9cf4-216fc7e694f0.png">
> 
> but the get user didn't.
> 
> <img alt="Capture d’écran 2020-07-03 à 20 26 26" width="805" src="https://user-images.githubusercontent.com/4179728/86493998-90665f80-bd6b-11ea-81ee-897f0170cb2d.png">

@sid3r, See my comment: https://github.com/tuandm/laravue/issues/185#issuecomment-652984764

**Comment by tuandm** [comment]
@sid3r  Seems it's Santcum setting. Please check [this issue](https://github.com/tuandm/laravue/issues/197). You should delete cookies after changing domain in .env file.

**Comment by jobinpankajan** [comment]
Working Fine, thank you for the support

**Comment by sid3r** [comment]
working fine here too, thank you for the support and the awesome work.
