### ISSUE TITLE
docker-compose up issue

### ISSUE THREAD

**Issue by mikhail-karan** [tuandm/laravue#187]
Hi,

Our team has recently decided to use Laravue as a base for our admin panel. We ran into an issue with the docker initialization though. 

When we run `docker-compose up -d` it doesn't seem to work, then I ran `docker-compose up` to see the output and it seems to be getting stuck on `nc -z $MYSQL_HOST $MYSQL_PORT && break` line in the laravue-entrypoint.sh file. (see issue below) It gets stuck on `: forward host lookup failed: Unknown host`

![image](https://user-images.githubusercontent.com/8340258/83776581-5a439c00-a656-11ea-91b9-aa4157638c01.png)

This happens on the master of laravue with no edits, for testing/reproduction purposes.

**Comment by jigzstar** [comment]
Make sure your docker/docker.env file is setup with the correct values (DB_HOST) used in the docker-compose.yml. The ```nc``` command seems to be failing. You can try commenting that line, and double check that laravel can connect to the db
