### ISSUE TITLE
Run production the js is to big, How to resolve it?

### ISSUE THREAD

**Issue by shanyul** [tuandm/laravue#188]
![微信截图_20200605095915](https://user-images.githubusercontent.com/31265100/83828634-bc160b80-a713-11ea-8502-520bdf6e2203.png)
![微信截图_20200605095534](https://user-images.githubusercontent.com/31265100/83828647-c20bec80-a713-11ea-8104-b96703fc7cf8.png)

Please help, thx.

**Comment by tuandm** [comment]
@shanyul 
Laravue appears as an rich-feature backend that requires many libraries/tools. You can go through all components and remove them if you don't have plan to use. Another approach is using [Lazy Loading Routes](https://router.vuejs.org/guide/advanced/lazy-loading.html).
