### ISSUE TITLE
How can i edit the admin password?

### ISSUE THREAD

**Issue by dssol** [tuandm/laravue#191]
Thx for the nice project!

I was wondering how to change the admin password

**Comment by khayyak** [comment]
here is an example to change password of the user
$user = Auth::user();
        $user->email = $request->email;
        
        $credentials = ['email' => $request->email, 'password' => $request->password];

if (Auth::guard('web')->attempt($credentials, false, false)) {
    if(strcmp($request->newPass , $request->confirmNewPass) == 0)
    {
        $user->password = Hash::make($request->newPass); 
    }

**Comment by tuandm** [comment]
@dssol It's not too hard to write code for this task. You can check sample code here:
https://github.com/tuandm/laravue/blob/master/app/Http/Controllers/Api/UserController.php
