### ISSUE TITLE
Go to http://127.0.0.1:8000/ will always redirect to http://127.0.0.1:8000/#/login?redirect=%2Fdashboard after added vendor.js,  manifest.js and app.js in welcome.blade.php.

### ISSUE THREAD

**Issue by LeonLoong** [tuandm/laravue#192]
## Description
I found out that Laravue is a good thing can let me manage stuff easily. 

I managed to separate the Laravue admin dashboard and my e-commerce website with modify **LARAVUE_PATH**. So that when public users enter the e-commerce welcome  page , no verification is required.

However, some problems were encountered during this operation and your help or suggestions are needed.

## App used
1. Laravue "version": "0.11.0"
2. Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)
3. Windows 10 home
4. VS Code

## Steps to reproduce
1. Install fresh Laravue
2. Change the LARAVUE_PATH=admin in .env file 
3. Setup vue.js in "laravue\resources\views\welcome.blade.php"
```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Laravel</title>

        {{-- Stylesheet --}}
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet">
        <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">
        <link href="{{ mix('css/app.css') }}" type="text/css" rel="stylesheet">
    </head>
    
    <body>
        Vue.js is not detected
        <div id="public-app">
            <example-component></example-component>
        </div>
        {{-- Scripts --}}
        <script src="{{ mix('js/vendor.js') }}"></script>
        <script src="{{ mix('js/manifest.js') }}"></script>
        <script src="{{ mix('js/app.js') }}"></script>
    </body>
</html>
```
4. Add another instance for public e-commerce page in "laravue\resources\js\app.js"
```
import Vue from 'vue';
import Cookies from 'js-cookie';
import ElementUI from 'element-ui';
import App from './views/App';
import store from './store';
import router from '@/router';
import i18n from './lang'; // Internationalization
import '@/icons'; // icon
import '@/permission'; // permission control

import * as filters from './filters'; // global filters

import exampleComponent from './components/ExampleComponent';

Vue.use(ElementUI, {
  size: Cookies.get('size') || 'medium', // set element-ui default size
  i18n: (key, value) => i18n.t(key, value),
});

// register global utility filters.
Object.keys(filters).forEach(key => {
  Vue.filter(key, filters[key]);
});

Vue.config.productionTip = false;

new Vue({
  el: '#app',
  router,
  store,
  i18n,
  render: h => h(App),
});

new Vue({
  el: '#public-app',
  components: {
    'example-component': exampleComponent,
  },
});
```
5. npm run watch / npm run dev
6. php artisan serve
7. goto http://127.0.0.1:8000/

### What is actually happening?
When I go to [http://127.0.0.1:8000/](http://127.0.0.1:8000/), it always redirect me to http://127.0.0.1:8000/#/login?redirect=%2Fdashboard
![Capture](https://user-images.githubusercontent.com/11975617/84674854-14dc7400-af5e-11ea-83e4-38ea79d1eb1a.PNG)

## What is expected?
Remain in same route without any redirect.

## Conclusion
I have tried added '/' to the whitelist in permission.js, based on this issue [#76](https://github.com/tuandm/laravue/issues/76), but no luck. When go to http://127.0.0.1:8000/ it still will redirect to login page.
Hopefully someone can help me, your assistance in this matter is greatly appreciate.

**Comment by tuandm** [comment]
@LeonLoong Thanks for reaching out this project and sorry for this late reply.
I don't think creating new Vue instance in laravue\resources\js\app.js will work as expected because it imports @/router which initializes Router instance.
In your case, I suggest to create another app.js and only load your necessary stuff. You may need to modify webpack.mix.js to compile your app.js and add to welcome.blade.php.

**Comment by kizinho** [comment]
i encounter same issues , since 24 hrs looking for what to do  but no solution

**Comment by LeonLoong** [comment]
@tuandm Thanks for your reply, I succeeded in achieving the result I wanted according to your suggestion, thank you very much. Your support is mean a lot to me!

@kizinho Based on @tuandm suggestion, below is my step to achieve this.

1. First, I renamed and copied the previous e-commerce (laravel + vue) app.js to jombateriapp.js to the same location as Laravue app.js
![step1](https://user-images.githubusercontent.com/11975617/87418297-038d9280-c604-11ea-9e5a-f84f541041e1.jpg)

2. I added the e-commerce jombateriapp.js to webpack.mix.js and then "run npm run dev" or "npm run watch". It will compile everything. When finished, you will see jombateriapp.js (compiled version) in "public/js"
![step2](https://user-images.githubusercontent.com/11975617/87418840-063cb780-c605-11ea-97b6-c331a8ed780e.jpg)

3. Modify welcome.blade.php.
![step3](https://user-images.githubusercontent.com/11975617/87419257-c2967d80-c605-11ea-871e-75172295530c.jpg)

4. run "php artisan serve" and go to http://127.0.0.1:8000/
![step4](https://user-images.githubusercontent.com/11975617/87419443-12754480-c606-11ea-9b65-0a963097b0b1.jpg)

5. when goto http://127.0.0.1:8000/admin , it will using laravue.blade.php and redirect to Laravue admin dashboard
![step6](https://user-images.githubusercontent.com/11975617/87419566-4a7c8780-c606-11ea-836f-c6ec4d9693a9.jpg)
 
The above resullts is based on my project and may differ from your situation.
