### ISSUE TITLE
404 error on sanctum/csrf-cookie

### ISSUE THREAD

**Issue by smccoy78** [tuandm/laravue#193]
When I try to login I am getting a 404 error regarding the sanctum/csrf-cookie url.

![Screen Shot 2020-06-12 at 8 08 37 PM](https://user-images.githubusercontent.com/2486409/84555068-f4f04a80-ace8-11ea-967c-cfb3afb07c88.png)

**Comment by omaralwi** [comment]
same problem after I publish project to cloud , but in Local it is running normal

**Comment by tuandm** [comment]
@smccoy78 It should request to /api/sanctum/csrf-cookie, not /sanctum/csrf-cookie. Do you have `MIX_BASE_API` setting on your .env file?
https://github.com/tuandm/laravue/blob/master/.env.example

**Comment by omaralwi** [comment]
Yes I made that probably ,, also these routes:
http://mydomain/api/sanctum/csrf-cookie
http://mydomain/api/auth/login
http:/mydomain/api/user

**Comment by tuandm** [comment]
@omaralwi That `MIX_BASE_API` should be `api` to make sure all API requests from client will send to API routes on server.

**Comment by smccoy78** [comment]
I was missing the MIX_BASE_API from my .env. However, I am still unable to login. The login function returns successful, but the getInfo() call is returning unauthenticated. I will create a new issue since this isn't related to original issue.
