### ISSUE TITLE
Update sidebar items

### ISSUE THREAD

**Issue by haizad** [tuandm/laravue#199]
Hi, I would like to know how to update sidebar items instead of setting it manually through public/js/app.js , as it seems hard to me configure. I tried search files related , such as _layout/components/Sidebar/SidebarItem.vue_ , I wonder if I can just set the sidebar items there..

The js/router/index.js which allows me to edit the route are more readable and easy to configure compared to the app.js file.

p/s : Pardon me for creating this issue, as I am still learning on how laravel SPA works. 

Thank you.

**Comment by tuandm** [comment]
@haizad Please check the documentation here: https://doc.laravue.dev/guide/development/new-page.html#add-the-route

**Comment by haizad** [comment]
How silly I am for not going thoroughly on the documentation. Thank you so much.
