### ISSUE TITLE
Login request is failing with Error 401. I am attaching the image

### ISSUE THREAD

**Issue by azhad-idlbridge** [tuandm/laravue#201]
Upon checking console I am seeing User request goes to 401. It returns unauthorized. I have strictly followed the instructions but do not know what is wrong here.
![Issue](https://user-images.githubusercontent.com/61963178/86361076-bbc64d00-bc8c-11ea-980d-66e934a247e5.png)
.

**Comment by smccoy78** [comment]
I am having the same issue.

**Comment by tuandm** [comment]
@azhad-idlbridge Please check this answer: https://github.com/tuandm/laravue/issues/197#issuecomment-653117775

**Comment by azhad-idlbridge** [comment]
Thank you very much for this assistance. You are awesome. I'll make sure you get a coffee from me.
