### ISSUE TITLE
MySQL database charset and collation

### ISSUE THREAD

**Issue by LeftPinkie** [tuandm/laravue#202]
A suggestion / enhancement...

In the `./config/database.php` file, change from:
```
55            'charset' => 'utf8mb4',
56            'collation' => 'utf8mb4_unicode_ci',
```
to:
```
55            'charset' => env('DB_CHARSET', 'utf8mb4'),
56            'collation' => env('DB_COLLATION', 'utf8mb4_unicode_ci'),
```

This will allow us to set the MySQL db charset and collation via the `.env` file.

**Comment by tuandm** [comment]
@LeftPinkie Thanks for your suggestion. Actually this project was forked from [Laravel official project](https://github.com/laravel/laravel). You can see original version here: https://github.com/laravel/laravel/blob/master/config/database.php

Changing files from the vendor is not recommended as we want to keep syncing with Laravel as much as possible
