### ISSUE TITLE
user/getInfo unauthenticated after successful login 

### ISSUE THREAD

**Issue by smccoy78** [tuandm/laravue#203]
After I successful login, I am getting 'unauthenticated' response when permission.js router.beforeEach attempts the getInfo call. It doesn't seem to be creating the token. I noticed that the personal_access_tokens table is not getting any entries, not sure if that is related. I haven't made any changes to the api routes file. I created a fresh project to make sure everything was up to date. I checked the request response from the login request and the user data is there. The isLogged() returns true. Any help would be appreciated.

**Comment by webtamizhan** [comment]
Hi there!

This is not the problem of this boilerplate!

You need to set the app url(host with tld) on your .env.

`SANCTUM_STATEFUL_DOMAINS="localhost,127.0.0.1,example.test,example.dev"`

and do `php artisan optimize:clear or php artisan config:cache`

**Comment by tuandm** [comment]
@webtamizhan Thanks for pointing out the issue here. 
@smccoy78 You may need to check this answer: https://github.com/tuandm/laravue/issues/197#issuecomment-653117775

**Comment by smccoy78** [comment]
I understand, thank you. Issue resolved.
