### ISSUE TITLE
Unauthenticated error in 0.12.0

### ISSUE THREAD

**Issue by altynbek07** [tuandm/laravue#204]
I installed version **0.12.0** and received **Unauthenticated.** error during authorization. Try reinstalling version 0.12.0, you will get this error. Also, the error alert is repeated twice. Attached a screenshot.
![image](https://user-images.githubusercontent.com/20629188/86522268-cd6a4900-be74-11ea-8d74-ee626a176ce3.png)

**Comment by tuandm** [comment]
@altynbek07 Seems it's Santcum setting. Please check [this issue](https://github.com/tuandm/laravue/issues/197). You should delete cookies after changing domain in .env file.

**Comment by altynbek07** [comment]
@tuandm Thank you. I use `Laravel Valet`. In `.env` file I added my domain `SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1,laravue.test`.
