### ISSUE TITLE
Cant continue to Laravue after hosting in AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by chaaawles** [tuandm/laravue#207]
I changed the LARAVUE_PATH to admin and hosted my laravue project in AWS EBS but can't reach the laravue path. I can see the homepage of Laravel but redirecting to Laravue produces an error. Tried hosting it on other sites and it works fine.

**Comment by tuandm** [comment]
@chaaawles What is that error? Is that site public?

**Comment by chaaawles** [comment]
An error 404. I changed the LARAVUE_PATH to admin and left the mix laravue path unchanged.

**Comment by tuandm** [comment]
Where did you run npm? Changing LARAVUE_PATH requires `npm run...` again. I can't think of any other reason since I don't have AWS EBS to test.

**Comment by chaaawles** [comment]
i run them before uploading. now it shows error 404 but in the api for login now

**Comment by tuandm** [comment]
@chaaawles Sorry we couldn't help here because we don't have AWS EBS to test.
