### ISSUE TITLE
on demand compenents, Element-ui build size

### ISSUE THREAD

**Issue by sid3r** [tuandm/laravue#210]
It would be nice if the on demande module loading is the default setup, only the necessary modules should be built to reduce build size.

Any idea how to do that, since I cant' make work.

**Comment by z790490122** [comment]
https://element.eleme.cn/#/en-US/component/quickstart   你可以看看这个链接

**Comment by thomaschangbuz** [comment]
I tried to use lazyloading with code-splitting to split to several small files from a big app.js, but it doesn't work.
https://doc.laravue.dev/guide/advanced/lazy-loading.html

**Comment by z790490122** [comment]
> I tried to use lazyloading with code-splitting to split to several small files from a big app.js, but it doesn't work.
> https://doc.laravue.dev/guide/advanced/lazy-loading.html

app.js 文件大小跟实际导入包有关系,你查看下app.js那些包有用,注释掉导入,或者分块导入,打包后app.js会变小.

**Comment by thomaschangbuz** [comment]
我已经解决的，可以看这里
https://github.com/tuandm/laravue/issues/216

> > I tried to use lazyloading with code-splitting to split to several small files from a big app.js, but it doesn't work.
> > https://doc.laravue.dev/guide/advanced/lazy-loading.html
> 
> app.js 文件大小跟实际导入包有关系,你查看下app.js那些包有用,注释掉导入,或者分块导入,打包后app.js会变小.

**Comment by tuandm** [comment]
Lazy-loading component has been fixed. Please check [release 0.13.0](https://github.com/tuandm/laravue/releases/tag/0.13.0)
