### ISSUE TITLE
I am unable to login to laravue app after following everything according to documentation.

### ISSUE THREAD

**Issue by abdul41265** [tuandm/laravue#214]
![401 error](https://user-images.githubusercontent.com/25523671/87871285-9d6c8b00-c9c8-11ea-9f53-1f8d59a00791.JPG)

**Comment by vikaswalia** [comment]
add your domain in .env file on line 
SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1 //HERE ADD YOUR DOMAIN

**Comment by abdul41265** [comment]
am running it on localhost.

**Comment by vikaswalia** [comment]
I was facing same problem and this solved
i am using vhost domain
SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1,laravue-master.test

**Comment by abdul41265** [comment]
Thank you @vikaswalia vhost worked for me.
