### ISSUE TITLE
Login error after installation - Request failed with status code 401

### ISSUE THREAD

**Issue by salmaomario** [tuandm/laravue#219]
I am working on Homestead 
after installing and trying to login i got this error "Request failed with status code 401" 

Here is the network error 
```
Request URL: localhost/api/user
Request Method: GET
Status Code: 401 Unauthorized
Remote Address: 192.168.5.5:80
Referrer Policy: no-referrer-when-downgrade
```
Although the  "/api/auth/login"  request returned with success 200

**Comment by tuandm** [comment]
@salmaomario It seems that santum is not configured correctly. Please check similar issues here:
- https://github.com/tuandm/laravue/issues/185
- https://github.com/tuandm/laravue/issues/214
- https://github.com/tuandm/laravue/issues/204

**Comment by seanlunar** [comment]
Im facing the same issue
Im using windows and localhost:8000
But still geting the error 401

**Comment by tuandm** [comment]
@seanlunar Have you checked the above comment, like https://github.com/tuandm/laravue/issues/185?

If possible, can you please share your .env?

**Comment by zainaldeen** [comment]
first make sure from your .env file and set your correct database setting 
then (important) make sure to make clear cache : 
1- php artisan cache:clear
2- php artisan config:cache
3- php artisan config:clear

then you should make seed 
php artisan db:seed
then retry to sign in again it should works

**Comment by LeonLoong** [comment]
I also had this issue after installing fresh Laravue today. I confirm that my database is correct because if I send {{URL}}api/auth/login in Postman, everything is fine.  
What I tried is install fresh XAMPP, fresh Laravue, delete Google browsing data (include Browsing history, Cookies, Cache).
After that I run
01. composer create-project tuandm/laravue pms
02. change .env
03. php artisan migrate --seed
04. npm install
05. npm audit fix
06. npm run watch
07. php artisan serve
08. goto http://127.0.0.1:8000/
09. sigin-in with id: admin@laravue.dev and pass: laravue
10. Error Request failed with status code 401 is showing.
Failed to load resource: the server responded with a status of 401 (Unauthorized)
5xhr.js?b50d:178 GET http://127.0.0.1:8000/api/user 401 (Unauthorized)

**Comment by tuandm** [comment]
@LeonLoong Thanks for your trying. I don't think version 0.13.0 will have issue with login since it doesn't change anything on authentication. The problem is that Laravue use Sanctum with session mode by default and that mode requires correct setting in .env file. I think I should add an option to allow Laravue running with token mode.
Anyway, I will double check 0.13.0 to be sure.

**Comment by tuandm** [comment]
@LeonLoong Thanks for that. I just tested 0.13.0 and got same issue, however `php artisan config:cache` resolved it. I think changing .env requires clearing configuration cache to be affected.

You can add debug code in `fromFrontend` method
```
    public static function fromFrontend($request)
    {

        $referer = Str::replaceFirst('https://', '', $request->headers->get('referer'));
        $referer = Str::replaceFirst('http://', '', $referer);
        $referer = Str::endsWith($referer, '/') ? $referer : "{$referer}/";

        $stateful = array_filter(config('sanctum.stateful', []));

        dd($stateful); // This should show value of SANCTUM_STATEFUL_DOMAINS in .env file as array

        return Str::is(Collection::make($stateful)->map(function ($uri) {
            return trim($uri).'/*';
        })->all(), $referer);
    }
```

**Comment by LeonLoong** [comment]
@tuandm thanks for your reply. 
Today, I tested 0.13.0 again and followed your suggestions. But there are still errors in my situation. But luckily I found this https://github.com/laravel/sanctum/issues/161#issuecomment-642568128
Following steps is what I use to solve the this authentication error.
1. I changed `SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1` to `SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000` in .env file.
2. `php artisan config:cache` (important) as your said.
3. `php artisan serve`
4. goto http://127.0.0.1:8000/
Now it seems that everything is settled.

**Comment by tuandm** [comment]
@LeonLoong Yes it is. I forgot to mention that `php artisan serve` will run at port 8000. I should have noted this in Laravue's guideline.

**Comment by bahman2216** [comment]
I just installed fresh last version and have same issue. Not solved with all previous comments.

**Comment by zainaldeen** [comment]
> 
> 
> I just installed fresh last version and have same issue. Not solved with all previous comments.

first of all make this change in your .env file _SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1_ to SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000
then make sure that your server run on port 8000

make this comands :
1- php artisan config:clear
2- php artisan config:cache
3- php artisan cache:clear

then you should shut your server and run it again 
now it should be work !

**Comment by multiarts** [comment]
> > I just installed fresh last version and have same issue. Not solved with all previous comments.
> 
> first of all make this change in your .env file _SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1_ to SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000
> then make sure that your server run on port 8000
> 
> make this comands :
> 1- php artisan config:clear
> 2- php artisan config:cache
> 3- php artisan cache:clear
> 
> then you should shut your server down and run it again : php artisan serve
> now it should be work !

This solved. Thk. :100:

**Comment by zainaldeen** [comment]
> > > I just installed fresh last version and have same issue. Not solved with all previous comments.
> > 
> > 
> > first of all make this change in your .env file _SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1_ to SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000
> > then make sure that your server run on port 8000
> > make this comands :
> > 1- php artisan config:clear
> > 2- php artisan config:cache
> > 3- php artisan cache:clear
> > then you should shut your server down and run it again : php artisan serve
> > now it should be work !
> 
> This solved. Thk. 💯

U r welcome ! 😁

**Comment by zainaldeen** [comment]
> > > I just installed fresh last version and have same issue. Not solved with all previous comments.
> > 
> > 
> > first of all make this change in your .env file _SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1_ to SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000
> > then make sure that your server run on port 8000
> > make this comands :
> > 1- php artisan config:clear
> > 2- php artisan config:cache
> > 3- php artisan cache:clear
> > then you should shut your server down and run it again : php artisan serve
> > now it should be work !
> 
> This solved. Thk. 💯

U r welcome ! 😁

**Comment by ikramkhizar** [comment]
If you are using laragon then add this
SANCTUM_STATEFUL_DOMAINS=localhost:8000,127.0.0.1:8000,laravue.test
