### ISSUE TITLE
SideBar Menu Color

### ISSUE THREAD

**Issue by waseidel** [tuandm/laravue#221]
Hi i'm currently using laravue to build 1 project, I'm pretty new to development, but I have found this issue, I'm trying to change the sidebar color from the file `variables.scss` the variable name I guess it was `$menuBg`, I changed and compiled but nothing happens, then i went to `layout/components/Sidebar/index.vue` and I found that is harcoded the `background-color="#304156"`, I still don't know how to put that in a variable (I'v already try some ways but nothing happens), I thing it should be changed to this variable to be concistent, the other colors have changed from the `variable.scss` file and works like a charm,

**Comment by nguyenquangtin** [comment]
Hello @waseidel,

Your issue should be fixed with the latest update of Laravue at [`Fix sidebar color`](https://github.com/tuandm/laravue/commit/fafaf6b29acd88c6ddd298c3ac19bc5736900cda).
