### ISSUE TITLE
Blocked by authorization even if the routes to be accessed is in constant routes

### ISSUE THREAD

**Issue by chaaawles** [tuandm/laravue#224]
I tried to add a register and reset your password pages on my laravue. But unfortunately I was kept on the login page. How can I get pass this without logging in?

**Comment by tuandm** [comment]
@chaaawles Your issue may be related with [this one](https://github.com/tuandm/laravue/issues/76)

**Comment by chaaawles** [comment]
I see. I just need to put my new route to the whitelist found in `js/permission.js`

`const whiteList = ['/login', '/auth-redirect']; // no redirect whitelist`

Thanks!
