### ISSUE TITLE
NPM or Yarn install is giving error

### ISSUE THREAD

**Issue by commencementtech** [tuandm/laravue#229]
![image](https://user-images.githubusercontent.com/66028734/90983968-a2a49300-e58f-11ea-95f2-b45bf5a7777f.png)

![image](https://user-images.githubusercontent.com/66028734/90983985-c071f800-e58f-11ea-92fb-f10e026bc9e9.png)

**Comment by tuandm** [comment]
@commencementtech It's not issue of Laravue. Your machine doesn't seem to work witth ssh:// protocol, please change to https://
https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe
```
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```
