### ISSUE TITLE
New Install - 405 on Login

### ISSUE THREAD

**Issue by BtotheT** [tuandm/laravue#23]
On first install (after key gen and config:cache):

`php artisan:serve`

Attempting to login via default credentials results in a 405 error.

> message: "The POST method is not supported for this route. Supported methods: GET, HEAD."

Route: /auth/login

**Comment by tuandm** [comment]
The correct route should be `/api/auth/login`, please check if your .env has those lines:
```
BASE_API=/api
MIX_BASE_API="${BASE_API}"
```

**Comment by budirec** [comment]
I think the issue is the env variable is not available.
Doing console.log(process.env) gives me error
process is undefined

**Comment by prawn185** [comment]
@budirec So how would you solve this?

**Comment by budirec** [comment]
For now what I do is hardcode /api in https://github.com/tuandm/laravue/blob/master/resources/js/utils/request.js#L7

But I think there should be better way to fix this, and need to investigate why the env var is not feed to the js

**Comment by tuandm** [comment]
That setting is on your .env, please check example in https://github.com/tuandm/laravue/blob/master/.env.example
```
BASE_API=/api
MIX_BASE_API="${BASE_API}"
```
This `MIX_BASE_API` value will be transfered to 
```
  baseURL: process.env.MIX_BASE_API,
```
Detail here: https://laravel.com/docs/5.8/mix#environment-variables

**Comment by budirec** [comment]
yeah, I have that in my .env but it wasn't available in the js file
process.env is undefined

`PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
BASE_API=/api

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
MIX_BASE_API="${BASE_API}"
MIX_WP_DOMAIN="${WP_DOMAIN}"`

**Comment by fpcimmino** [comment]
I have same problem. Do you help me?

**Comment by tuandm** [comment]
Changing .env required `npm run` again
