### ISSUE TITLE
Failed run test/phpunit

### ISSUE THREAD

**Issue by ganjarsetia** [tuandm/laravue#233]
when I run `phpunit` its failed, if I create new laravel project with same test, its succeed. 
How to fix this issue?

![image](https://user-images.githubusercontent.com/3258090/91526873-cf113400-e92e-11ea-938a-8f40cb58a80c.png)

**Comment by tuandm** [comment]
@ganjarsetia  What's your APP_URL in test environment (in `.env` or `.env.testing`)? `php artisan test` or `./vendor/bin/phpunit ./tests/` work in my side (fresh installation).

**Comment by ganjarsetia** [comment]
@tuandm I'm using `.env` & `.env.testing` the contents is same

```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:q0GwY69KKcboi+QZvW5k4s1imrBJqssk2x2ZVQymhqg=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
SANCTUM_STATEFUL_DOMAINS=localhost,127.0.0.1,127.0.0.1:8000


MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

BASE_API=/api
LARAVUE_USE_ESLINT=true
LARAVUE_PATH=
MIX_BASE_API="${BASE_API}"
MIX_LARAVUE_PATH="${LARAVUE_PATH}"
```

I modified the `phpunit.xml` just uncomment 2 lines to be like this:

```XML
<server name="DB_CONNECTION" value="sqlite"/>
<server name="DB_DATABASE" value=":memory:"/>
```

After I run `php artisan test` & `./vendor/bin/phpunit ./tests/` still getting failed.

![image](https://user-images.githubusercontent.com/3258090/91652887-6b6d3f00-eac5-11ea-90e5-eff832dd3a88.png)

**Comment by ganjarsetia** [comment]
My PHP version is 7.4

When I run using docker & upgrade the PHP to 7.4, it all works.
I think my PHP installation is broken, I will close it now.

**Comment by tuandm** [comment]
@ganjarsetia You can check storage/logs/laravel.log for the error detail. If you didn't run `npm install` and `npm run dev/watch/production` before, you would get the error related to missing manifest file.

**Comment by ganjarsetia** [comment]
@tuandm sure thanks.

Btw this is OOT. Can I make PR of:

- Upgrade to PHP 7.3 in docker?
- Add Vue testing with Jest?

**Comment by tuandm** [comment]
Thanks @ganjarsetia. PRs are always welcome.

- PHP 7.3 in docker is good, just noted that Laravel still supports PHP [7.2.5](https://github.com/laravel/laravel/blob/master/composer.json) so better to keep that in Laravue.
- Testing is in our plan for long but we haven't made big steps on that. We are much appreciated if you can help us :).
