### ISSUE TITLE
Where is the cookie expiration time set after logging in

### ISSUE THREAD

**Issue by fenglijunnb** [tuandm/laravue#235]
hello,,Now I want to set the login invalidation time of cookie. I don't know how to set it

**Comment by tuandm** [comment]
@fenglijunnb By default, Laravue uses Laravel's built-in cookie based session which defines expiration time by  `SESSION_LIFETIME` in .env. You can change it to value (in minutes) you want. Ex:
```
SESSION_LIFETIME=1 # 1 minute
```
