### ISSUE TITLE
it is very slow first time

### ISSUE THREAD

**Issue by omaralwi** [tuandm/laravue#238]
when customer try to open system first time the page is vey slow because the huge size of Js files , all js files size is 46MB (vendor,manifestapp) any solutaion for this.?

**Comment by tuandm** [comment]
@omaralwi You may need to check [lazy-loading ](https://doc.laravue.dev/guide/advanced/lazy-loading.html#lazy-loading-route-in-laravue) and remove unused components.

More info here: https://github.com/tuandm/laravue/issues/210

**Comment by omaralwi** [comment]
yes it is solved, thank you very much for your great job

**Comment by mostafaabozied** [comment]
> 
> 
> yes it is solved, thank you very much for your great job

sorry bro i have the same , how you solve it

**Comment by omaralalwi** [comment]
https://doc.laravue.dev/guide/advanced/lazy-loading.html#lazy-loading-route-in-laravue

and make sure to run
 npm run dev

**Comment by mostafaabozied** [comment]
> 
> 
> https://doc.laravue.dev/guide/advanced/lazy-loading.html#lazy-loading-route-in-laravue
> 
> and make sure to run
> npm run dev

i did this stitll vendor is 28MB and app around 13 md

**Comment by omaralalwi** [comment]
no I am sure if you run npm run production ,, sorry I mean npm run production it comparse to 4mb.

**Comment by mostafaabozied** [comment]
the page load the same js with the big sizes and load the small one too :)

**Comment by omaralalwi** [comment]
clear cache

**Comment by mostafaabozied** [comment]
i have old ver from laravue before #210 are this may be the resone ?
