### ISSUE TITLE
can not log in (error 401)

### ISSUE THREAD

**Issue by jmartsch** [tuandm/laravue#254]
I made a fresh install and migrated the database, then I try to login with default credentials:
Email: admin@laravue.dev
Pass: laravue

but I get `Request failed with status code 401` for the user route
The message of the XHR Request in dev tools says "unauthenticated"

The return of the login route XHR reads
```{success: true, data: {id: 1, name: "Admin", email: "admin@laravue.dev", roles: ["admin"],…},…}
data: {id: 1, name: "Admin", email: "admin@laravue.dev", roles: ["admin"],…}
error: ""
success: true
```

Can you help me solve this problem?

**Comment by jmartsch** [comment]
Ok, it turned out, that I had to add my domain laravue.localhost to SANCTUM_STATEFUL_DOMAINS in the .env file

**Comment by fawel11** [comment]
It worked for me too.

**Comment by jggj21** [comment]
This worked for me.

**Comment by massimodevitis** [comment]
now This worked for me
br
Max

**Comment by mnadeemijaz** [comment]
i have the same issue 
but I have made virtual host idlpost.test
how can I resolve this issue

APP_URL=http://idlpos.test/

SESSION_DOMAIN=idlpos.test

SANCTUM_STATEFUL_DOMAINS=idlpos.test

any help please
