### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by vulam8x** [tuandm/laravue#256]
After I installed it, there was a problem with login.

**Comment by tuandm** [comment]
@vulam8x There were many 401-related issues, please check [here](https://github.com/tuandm/laravue/issues?q=is%3Aissue+is%3Aclosed+401)

**Comment by vulam8x** [comment]
I added the Local domain to SANCTUM_STATEFUL_DOMAINS in the .env file and it worked
Thanks for the feedback
