### ISSUE TITLE
@keyup.enter.native="handleFilter" not working

### ISSUE THREAD

**Issue by vulam8x** [tuandm/laravue#260]
I enter keyword to search but the results are only done when clicking on the search button in the user search

**Comment by TChrabanski** [comment]
Change:
`@keyup.enter.native="handleFilter"`

to

`@input="handleFilter"`

**Comment by vulam8x** [comment]
thank you! it worked.

**Comment by vulam8x** [comment]
> Change:
> `@keyup.enter.native="handleFilter"`
> 
> to
> 
> `@input="handleFilter"`
