### ISSUE TITLE
Demo app its not running

### ISSUE THREAD

**Issue by daav7713** [tuandm/laravue#276]
Hi, sorry to report this here but i dont know other place to do it, but the demo application https://laravue.dev/ have an issue on login, it throws a 500 error when you try to login.

![image](https://user-images.githubusercontent.com/15809768/104322252-56a8ab00-54aa-11eb-8781-4a6c29d6edaf.png)

**Comment by tuandm** [comment]
@daav7713 Sorry for that issue, it should be fixed now. It's the server issue, not the app one.
