### ISSUE TITLE
CASL package check permissions 

### ISSUE THREAD

**Issue by codetay** [tuandm/laravue#296]
Có ý định dùng casl package không bác ?

Nãy xem thử demo permission mà cái phần chuyển role nó đơ luôn trình duyệt có vẻ crash code hay gì đó. Nên khả năng có bug ở phần check role.

Cái package casl kia khá nhiều bên dùng không biết bác có ý định chuyển không ?

**Comment by tuandm** [comment]
@codetay phần chuyển role trong permission nó sẽ đẩy về 404 nếu  target role không có permission ờ trang hiện tại, nên có thể bạn thấy "đơ", nhưng thực chất là nó đá về 404 liên tục. 
Casl package khá là ổn, works well với Spatie/laravel-permission và Sanctum, bạn có thể xem demo ở chỗ này: https://github.com/deal-makers/laravel7-vuexy-sanctum-spa-demo. Trong phạm vi Laravue thì mình không muốn add vào quá nhiều package vì sẽ mất tính linh hoạt của framework, chỉ cung cấp very basic features. Tuy nhiên mình sẽ check xem nếu có thể đưa casl vào.

**Comment by codetay** [comment]
Hiện tại thì mình đã dùng casl cho các project của mình rồi, chỉ gợi ý bạn dùng nó vì tính uyển chuyển phù hợp với nhiều loại object permissions khác nhau thôi. Thêm cái vụ test lag + crash luôn trình duyệt đối với permission bạn đang check array đó nên mình mới gợi ý cho bạn dùng casl để thay thế và cũng là sau này tương thích với nhiều loại permissions khác
