### ISSUE TITLE
the code of vue changed but the page not change

### ISSUE THREAD

**Issue by DamonSnow** [tuandm/laravue#301]
![image](https://user-images.githubusercontent.com/18485833/118744859-a7c91100-b887-11eb-84fd-7f451662c59c.png)
npm run watch is worked.
but when i change the code of vue, like that I add a column 'avatar' in [views/users/List.vue].
![image](https://user-images.githubusercontent.com/18485833/118745136-28880d00-b888-11eb-8457-e6beeb8fbaf0.png)
after auto reload, the page does not change.
![image](https://user-images.githubusercontent.com/18485833/118745221-4fdeda00-b888-11eb-8a8e-b59a169e84e9.png)

**Comment by MarcosGit** [comment]
Hi, DamonSnow, try this
`php artisan view:clear`
`php artisan cache:clear`

**Comment by yjy1200** [comment]
ctrl + F5

**Comment by DamonSnow** [comment]
i try this, and it's work
`npm run watch-poll`
