### ISSUE TITLE
Expired SSL of Laravue

### ISSUE THREAD

**Issue by mightypeng** [tuandm/laravue#317]
Hi sir tuandm,

Good day!

Just want to report inaccessibility of Laravue in Live right now due to SSL problem.
Please see the screenshot below. Thank you.

![image](https://user-images.githubusercontent.com/85773527/131494142-6c71dfd3-afe6-476b-9c5c-11e0a6395267.png)

**Comment by tuandm** [comment]
@mightypeng Thanks for your report. It is fixed now.
