### ISSUE TITLE
can't find the articles api route config 

### ISSUE THREAD

**Issue by jestersimpps** [tuandm/laravue#32]
Hi, I'm having trouble finding the endpoint config of the articles route.
I was expecting it to be in the routes/api file.

**Comment by tuandm** [comment]
Thanks for reaching this project. Next release will fix this route issue. In the meantime, you can add article route to vendor/tuandm/laravue-core/src/routers/laravue.php. Sorry for this problem. I will add fix soon.

**Comment by jestersimpps** [comment]
Thank you for your response. And thank you for the framework. It has great potential. Keep up the good work 👍

**Comment by Stdubic** [comment]
the same problem to me here, any news?

**Comment by Stdubic** [comment]
in vendor, ServiceProvider.php overwrites the default one

protected function registerRoutes()
    {
        $this->loadRoutesFrom(__DIR__ . '/routes/laravue.php')
to:
///->$this->loadRoutesFrom(base_path('routes/api.php'));
    }

this will activate base routes/api.php in laravel

Please fix this issue in vendor.

I would like to thank you for the great work :)

I will follow and contribute if you have any issues fell free to contact me

**Comment by tuandm** [comment]
@Stdubic: Thanks for pointing the issue - actually it is fixed and will be released next time. You can check the [before-release](https://github.com/tuandm/laravue/tree/feature/before-release) branch for the latest updates

**Comment by tuandm** [comment]
#33
