### ISSUE TITLE
Certificate on laravue.dev expired on 02/03/2022. Currently cannot access the site at all.

### ISSUE THREAD

**Issue by jason-newvision** [tuandm/laravue#332]
Hi, 

The SSL Certificate on laravue.dev expired on 02/03/2022. Currently it is not possible to access the site.

Please could you look into this?

Kind regards
Jason

**Comment by tuandm** [comment]
Hi @jason-newvision
This issue is fixed. Thanks for the report.

**Comment by jason-newvision** [comment]
Hi @tuandm . Thanks for sorting so quickly!
