### ISSUE TITLE
Mix manifest not found when running docker

### ISSUE THREAD

**Issue by virutmath** [tuandm/laravue#338]
![image](https://user-images.githubusercontent.com/1576480/166445803-41cbc17e-caa6-4858-9824-53bd65d11ab0.png)
When I pull source code and run docker-compose up, the error is occur

The Mix manifest does not exist. (View: /var/www/resources/views/laravue.blade.php)

 if (! isset($manifests[$manifestPath])) {

            if (! file_exists($manifestPath)) {

                throw new Exception('The Mix manifest does not exist.');

            }

 

            $manifests[$manifestPath] = json_decode(file_get_contents($manifestPath), true);

        }

**Comment by HuyPham55** [comment]
Looks like they've abandoned the project. Last update was in 2021

**Comment by zanyar-ahmed** [comment]
Then what's their plan for this issue?

**Comment by ngdangdat** [comment]
@virutmath 
I've upgraded the Docker image to match the Laravel version. Please help to check if the issue still remains.

PR for reference: https://github.com/tuandm/laravue/pull/349
