### ISSUE TITLE
Npm install

### ISSUE THREAD

**Issue by laurence702** [tuandm/laravue#36]
I cant seem to get project to work,
After I install all(node-sass always fails), and I try npm run dev, it throws a complain that It cant find node-sass.

 ive tried "sudo npm install --save-dev  --unsafe-perm node-sass"

I use a linux. ive granted all permissions on the node_modules folder recursively. seeing this project im so eager t test it but wont work for me.

Sorry for the noob question by the way

**Comment by tuandm** [comment]
Can you please share the error message here? My [laravue.dev](https://laravue.dev) server is CentOS 7.0 and it is working fine

**Comment by J0hnnyDaniel** [comment]
I may have the same issue, these are my error messages

ERROR in ./resources/js/components/HeaderSearch/index.vue?vue&type=style&index=0&id=430ffe83&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/HeaderSearch/index.vue?vue&type=style&index=0&id=430ffe83&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    /deep/ .el-input__inner {
   ^
      Expected selector.
    ╷
171 │     /deep/ .el-input__inner{
    │     ^
    ╵
  stdin 171:5  root stylesheet
      in /var/www/laravue/resources/js/components/HeaderSearch/index.vue (line 171, column 5)
 @ ./resources/js/components/HeaderSearch/index.vue?vue&type=style&index=0&id=430ffe83&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/HeaderSearch/index.vue?vue&type=style&index=0&id=430ffe83&lang=scss&scoped=true&) 2:14-401
 @ ./resources/js/components/HeaderSearch/index.vue?vue&type=style&index=0&id=430ffe83&lang=scss&scoped=true&
 @ ./resources/js/components/HeaderSearch/index.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/components/Navbar.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/components/Navbar.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/components/Navbar.vue
 @ ./resources/js/layout/components/index.js
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/index.vue
 @ ./resources/js/router/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/js/styles/index.scss

ERROR in ./resources/js/views/dashboard/admin/components/BoxCard.vue?vue&type=style&index=1&id=500f75fc&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/dashboard/admin/components/BoxCard.vue?vue&type=style&index=1&id=500f75fc&rel=stylesheet%2Fscss&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    /deep/ .pan-info {
   ^
      Expected selector.
    ╷
103 │     /deep/ .pan-info{
    │     ^
    ╵
  stdin 103:5  root stylesheet
      in /var/www/laravue/resources/js/views/dashboard/admin/components/BoxCard.vue (line 103, column 5)
 @ ./resources/js/views/dashboard/admin/components/BoxCard.vue?vue&type=style&index=1&id=500f75fc&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/dashboard/admin/components/BoxCard.vue?vue&type=style&index=1&id=500f75fc&rel=stylesheet%2Fscss&lang=scss&scoped=true&) 2:14-455
 @ ./resources/js/views/dashboard/admin/components/BoxCard.vue?vue&type=style&index=1&id=500f75fc&rel=stylesheet%2Fscss&lang=scss&scoped=true&
 @ ./resources/js/views/dashboard/admin/components/BoxCard.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/dashboard/admin/index.vue?vue&type=script&lang=js&
 @ ./resources/js/views/dashboard/admin/index.vue?vue&type=script&lang=js&
 @ ./resources/js/views/dashboard/admin/index.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/dashboard/index.vue?vue&type=script&lang=js&
 @ ./resources/js/views/dashboard/index.vue?vue&type=script&lang=js&
 @ ./resources/js/views/dashboard/index.vue
 @ ./resources/js/router/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/js/styles/index.scss

ERROR in ./resources/js/components/Tinymce/components/EditorImage.vue?vue&type=style&index=0&id=1f258700&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Tinymce/components/EditorImage.vue?vue&type=style&index=0&id=1f258700&rel=stylesheet%2Fscss&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  /deep/ .el-upload--picture-card {
 ^
      Expected selector.
   ╷
99 │   /deep/ .el-upload--picture-card{
   │   ^
   ╵
  stdin 99:3  root stylesheet
      in /var/www/laravue/resources/js/components/Tinymce/components/EditorImage.vue (line 99, column 3)
 @ ./resources/js/components/Tinymce/components/EditorImage.vue?vue&type=style&index=0&id=1f258700&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Tinymce/components/EditorImage.vue?vue&type=style&index=0&id=1f258700&rel=stylesheet%2Fscss&lang=scss&scoped=true&) 2:14-444
 @ ./resources/js/components/Tinymce/components/EditorImage.vue?vue&type=style&index=0&id=1f258700&rel=stylesheet%2Fscss&lang=scss&scoped=true&
 @ ./resources/js/components/Tinymce/components/EditorImage.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/components/Tinymce/index.vue?vue&type=script&lang=js&
 @ ./resources/js/components/Tinymce/index.vue?vue&type=script&lang=js&
 @ ./resources/js/components/Tinymce/index.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/components-demo/Tinymce.vue?vue&type=script&lang=js&
 @ ./resources/js/views/components-demo/Tinymce.vue?vue&type=script&lang=js&
 @ ./resources/js/views/components-demo/Tinymce.vue
 @ ./resources/js/router/modules/components.js
 @ ./resources/js/router/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/js/styles/index.scss

ERROR in ./resources/js/views/permission/Directive.vue?vue&type=style&index=0&id=22b939ee&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/permission/Directive.vue?vue&type=style&index=0&id=22b939ee&rel=stylesheet%2Fscss&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  /deep/ .permission-alert {
 ^
      Expected selector.
    ╷
128 │   /deep/ .permission-alert{
    │   ^
    ╵
  stdin 128:3  root stylesheet
      in /var/www/laravue/resources/js/views/permission/Directive.vue (line 128, column 3)
 @ ./resources/js/views/permission/Directive.vue?vue&type=style&index=0&id=22b939ee&rel=stylesheet%2Fscss&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/views/permission/Directive.vue?vue&type=style&index=0&id=22b939ee&rel=stylesheet%2Fscss&lang=scss&scoped=true&) 2:14-427
 @ ./resources/js/views/permission/Directive.vue?vue&type=style&index=0&id=22b939ee&rel=stylesheet%2Fscss&lang=scss&scoped=true&
 @ ./resources/js/views/permission/Directive.vue
 @ ./resources/js/router/modules/permission.js
 @ ./resources/js/router/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/js/styles/index.scss

ERROR in ./resources/js/layout/components/TagsView/ScrollPane.vue?vue&type=style&index=0&id=6d7a7ea4&lang=scss&scoped=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/components/TagsView/ScrollPane.vue?vue&type=style&index=0&id=6d7a7ea4&lang=scss&scoped=true&)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  /deep/ {
 ^
      Expected selector.
   ╷
76 │   /deep/{
   │   ^
   ╵
  stdin 76:3  root stylesheet
      in /var/www/laravue/resources/js/layout/components/TagsView/ScrollPane.vue (line 76, column 3)
 @ ./resources/js/layout/components/TagsView/ScrollPane.vue?vue&type=style&index=0&id=6d7a7ea4&lang=scss&scoped=true& (./node_modules/style-loader!./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/lib/loader.js??ref--7-3!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/components/TagsView/ScrollPane.vue?vue&type=style&index=0&id=6d7a7ea4&lang=scss&scoped=true&) 2:14-421
 @ ./resources/js/layout/components/TagsView/ScrollPane.vue?vue&type=style&index=0&id=6d7a7ea4&lang=scss&scoped=true&
 @ ./resources/js/layout/components/TagsView/ScrollPane.vue
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/components/TagsView/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/components/TagsView/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/components/TagsView/index.vue
 @ ./resources/js/layout/components/index.js
 @ ./node_modules/babel-loader/lib??ref--4-0!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/layout/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/index.vue?vue&type=script&lang=js&
 @ ./resources/js/layout/index.vue
 @ ./resources/js/router/index.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/js/styles/index.scss

**Comment by tuandm** [comment]
@J0hnnyDaniel Which is your laravel-mix's version? This issue should be fixed since Laravel-Mix 4.0.4. Ref: https://github.com/JeffreyWay/laravel-mix/issues/1850

**Comment by tuandm** [comment]
`/deep/` issue should be resolved now.

**Comment by Johardmeier** [comment]
Get the same problem with a fresh install in windows
