### ISSUE TITLE
fsevents vulnerability

### ISSUE THREAD

**Issue by prawn185** [tuandm/laravue#38]
So im doing everything prior and I get this error when I run `npm install`

https://pastebin.com/zdcMpVzQ

**Comment by prawn185** [comment]
Ok great thanks, i'll give it another shot

**Comment by prawn185** [comment]
@tuandm So I don't know if i'm doing something wrong but i've gone though the installtion steps but i'm getting a blank screen with the HTML code like this: 
`

  | <!doctype html>
-- | --
  | <html lang="en">
  | <head>
  | <meta charset="UTF-8">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  | <meta http-equiv="X-UA-Compatible" content="ie=edge">
  | <title>Laravel Vue Admin</title>
  |  
  | <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
  | <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
  | <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
  | <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
  | <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
  | <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
  | <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
  | <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
  | <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
  | <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
  | <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
  | <link rel="manifest" href="/favicon/manifest.json">
  | <meta name="msapplication-TileColor" content="#ffffff">
  | <meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
  | <meta name="theme-color" content="#ffffff">
  | <link href="/css/app.css?id=931771ec270f069ffa01" type="text/css" rel="stylesheet" />
  | </head>
  | <body>
  | <div id="app">
  | <app></app>
  | </div>
  |  
  | <script src=/static/tinymce4.7.5/tinymce.min.js></script>
  | <script src="/js/vendor.js?id=374be93cf8d303ea1f46"></script>
  | <script src="/js/manifest.js?id=227795a4cf81cedbd601"></script>
  | <script src="/js/app.js?id=a09bf6287c62d3941912"></script>
  | </body>
  | </html>
  |  

`

**Comment by tuandm** [comment]
@prawn185 Just to make sure your machine is ready.
1. Have you run Laravel project on your machine before? Just to make sure your PHP/web server is ready.
2. Does `npm run dev` or `npm run watch` works without error?

**Comment by prawn185** [comment]
Yeah, I am using Laragon as I'm having issues with Homestead.
I have a current Laravel project working on the same "server"
And both compile just fine

**Comment by tuandm** [comment]
@prawn185 Sorry I don't have Windows machine here to reproduce your issue. But Laravue works fine with Windows due to other feedbacks. If your page is blank, I think the problem seems related to webpack - the JS file is not compiled correctly.

**Comment by prawn185** [comment]
@tuandm  Here is when I run npm run dev
https://pastebin.com/NM7rAJr2
I think going to try and stick it on a webserver I have :L

**Comment by tuandm** [comment]
@prawn185 Thanks for your try. Your npm command seems fine. Doesn't have any error in browser's console?
