### ISSUE TITLE
500 Error on login

### ISSUE THREAD

**Issue by prawn185** [tuandm/laravue#40]
Hi it's me again... So ive have no installed it on my Homestead but cannot login, am I forgetting something?

api/auth/login 500 (Internal Server Error) (in console)

Request failed with status code 500

**Comment by tuandm** [comment]
@prawn185 Hi, if error 500 means it should have something in the log file. Can you please open the chrome console - network tab to see the result of api call?

**Comment by prawn185** [comment]
Ok here, surly this means it can't connect to my database?
`exception: "Illuminate\Database\QueryException"
file: "/home/vagrant/code/ranch/laravue/vendor/laravel/framework/src/Illuminate/Database/Connection.php"
line: 664
message: "SQLSTATE[HY000] [2002] Connection refused (SQL: select * from `users` where `email` = admin@laravue.dev limit 1)"`

**Comment by prawn185** [comment]
Nevermind... I changed 127.0.0.1 in .env to localhost
