### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by moetanahy** [tuandm/laravue#44]
First of all, the admin panel looks fantastic!  We've just started using Vue JS as SPA application on top of Laravel, so this looks perfect.

My question (and I'm not sure this is the right place to ask it), is when will this be packaged into a library, so that we don't have all the components and laravue code throughout the application.

I wanted to be able to use this for a project, but it'll be quite difficult to differentiate our code from laravue.  Also, do you have any guidance/docs for how to create new pages, update the nav, etc, to get started? Thanks in advance.

**Comment by tuandm** [comment]
@moetanahy Thanks for reaching here. 
- This project is positioning for starting a project from scratch, so it's not suitable to integrate with ongoing projects. After installation, you can remove/modify the Laravue components to fit with your business requirements.
- We are working on the documentation and will release it next month.

**Comment by moetanahy** [comment]
Thanks @tuandm 

Thanks for getting back to me on each point.  I'm testing it out on a new side project - so far everything looks good, (just some challenges figuring out certain things - but I'll get there in the end).

Please let me know when documentation comes out, as that would help alot.

Again, great work and appreciate the efforts.

**Comment by djar00** [comment]
@tuandm thanks!!!

Project is great. I'm typical backend developer with Laravel, I can do it frontend :)

**Comment by tuandm** [comment]
@moetanahy You can find the very first version of documentation here: https://doc.laravue.dev

**Comment by tuandm** [comment]
@moetanahy @djar00
We would like to ask your approval to use your comments on our website as a testimonials? We may use your names, avatars and github urls as the credit. Let me know if you have any concern.

Regards,
Tuan Duong
