### ISSUE TITLE
Issue with latest IE (version 11)

### ISSUE THREAD

**Issue by sargishovnannisyan** [tuandm/laravue#46]
I thought that issue is only for local version, but error in console you can see also https://laravue.dev.

Scripts, that was built by webpack, are not minified in my local version, and seems issue is related with ./node_modules/camelcase/index.js.

to be more accurate, this part

`	const preserveCamelCase = string => {
		let isLastCharLower = false;
		let isLastCharUpper = false;
		let isLastLastCharUpper = false;

		for (let i = 0; i < string.length; i++) {
			const character = string[i];

			if (isLastCharLower && /[a-zA-Z]/.test(character) && character.toUpperCase() === character) {
				string = string.slice(0, i) + '-' + string.slice(i);
				isLastCharLower = false;
				isLastLastCharUpper = isLastCharUpper;
				isLastCharUpper = true;
				i++;
			} else if (isLastCharUpper && isLastLastCharUpper && /[a-zA-Z]/.test(character) && character.toLowerCase() === character) {
				string = string.slice(0, i - 1) + '-' + string.slice(i - 1);
				isLastLastCharUpper = isLastCharUpper;
				isLastCharUpper = false;
				isLastCharLower = true;
			} else {
				isLastCharLower = character.toLowerCase() === character && character.toUpperCase() !== character;
				isLastLastCharUpper = isLastCharUpper;
				isLastCharUpper = character.toUpperCase() === character && character.toLowerCase() !== character;
			}
		}

		return string;
	};`

And seems issue is with const declaration.

I've have done some research, tried one on the babel plugins, but that doesn't work for me.

Screenshot from my local version 
https://www.screencast.com/t/AtYN0vMfR

and from the demo, that you have hosted
https://www.screencast.com/t/LAXTXoqT2cfq

And navigating through error I'm getting to line
https://www.screencast.com/t/GuShyy70VSIm

Any solution, that you can suggest please ?

**Comment by tuandm** [comment]
@sargishovnannisyan Many thanks for pointing out this error. I will install IE to test the whole system.
(I'm Mac's user)

**Comment by tuandm** [comment]
@sargishovnannisyan The issue has been fixed.
