### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by medaharrat** [tuandm/laravue#47]
Before runing
`php artisan migrate --seed`
try adding **Schema::defaultStringLength('191')** to the **AppServiceProvider**, or you might face problems migrating.

**Comment by tuandm** [comment]
@digforfame I'm working on MySQL 5.7 and don't have that limitation. It's probably the issue of Laravel with old MySQL.
Thank you, I will note to the guidelines.

**Comment by MRUBS** [comment]
All you have to do is edit your AppServiceProvider.php file and inside the boot method set a default string length:

use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}

and after saving that, run these commands,

php artisan migrate
php artisan migrate --seed

**Comment by medaharrat** [comment]
@MRUBS Yeah, that was exactly what I said.
