### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by natb2005** [tuandm/laravue#50]
hello, I know that this in not an issue, but if i want to add new item in menu, or remove some one, which file I should edit?
I new how to create files and add them to route 
thank you all :)

**Comment by tuandm** [comment]
@natb2005 We are still working on documentation to provide a full guideline on how to work with Laravue in detail. In the meantime, this doc may help you: https://github.com/tuandm/laravue-doc/blob/master/docs/guide/essentials/new-page.md

**Comment by natb2005** [comment]
Yes It help me very much, thank you :)
