### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by tsbi11** [tuandm/laravue#51]
Not an issues - but where can we post questions?

A. Is there a blank starter without all the mock data and preset routes? If not what is safest way to strip out all pre-built routes etc?
B. The project is an SPA which loads the admin panel directly correct?  What would be best option to route to a public front end that loads instead of the dashboard before the admin login?   This way we can just link to the Dashboard login?

The documentation is great, thanks for hard work.

**Comment by tuandm** [comment]
@tsbi11 Thanks for reaching this project.
A. As the plan, this project is to provide full components and examples and become a guideline for developers can apply to their project. Actually the current routes/mock data are simple and easy to remove. Vue components are lazyloading so they won't be included if they are not used. I will create a document for removing mock data and preset routes.
B. Good point, I will create a document for this too, and create a landing page for laravue.dev instead the dashboard like the current one.

**Comment by junedc** [comment]
Hi @tuandm ,

First of all this is a great stuff you got here.  I was looking into documentation and looking for the 'landing page'.  Can you point me to the docs if its already done.  Thanks.

**Comment by tuandm** [comment]
@junedc Now Laravue can be configured to show as subfolder, then Laravel default landing page will show as usual. Please check the document here: https://doc.laravue.dev/guide/#change-the-path
