### ISSUE TITLE
Unable to locate Mix file: /js/vendor.js

### ISSUE THREAD

**Issue by milad777v2** [tuandm/laravue#52]
hello 
First of all. Excelent Job!!!
project is ok but then i copy in my project 
Unable to locate Mix file: /js/vendor.js

**Comment by hakankozakli** [comment]
Same issue here. How can we change the URLs when we are setting it up on a subfolder? Thanks for the great work btw!

**Comment by tuandm** [comment]
`vendor.js` will be extracted with `mix.extract([...])`, have you run `npm run dev/production/watch` to generate that file? 
Ref: https://laravel.com/docs/5.8/mix#vendor-extraction

**Comment by hakankozakli** [comment]
No the file extracts just fine. Only the path is wrong because it shows like /js/vendor.js but it actually needs to be /laravue/public/js/vendor.js or js/vendor.js. Not sure where I can change that.

**Comment by tuandm** [comment]
I see, so you are copying files over your own projects. Please correct the path of mix files here: https://github.com/tuandm/laravue/blob/master/resources/views/laravue.blade.php according to your project structure.

**Comment by hakankozakli** [comment]
Thanks for the fast response but the issue is {{ mix('js/vendor.js') }} this is creating /js/vendor.js as output. I need it to show js/vendor.js or complete relative path. How can I do that?

**Comment by tuandm** [comment]
@hakankozakli It depends on your folder structure, you can change `{{ mix('js/vendor.js') }}` to your actual path, such as `{{ mix('laravue/public/js/vendor.js') }}`. Alternatively, you can change the compiled folder of mix in `https://github.com/tuandm/laravue/blob/master/webpack.mix.js`: 
```
mix
  .js('resources/js/app.js', 'public/js') // change to your own folder
```

Sorry, I'm not sure I'm understanding correctly your issue, just a guess :).

**Comment by hakankozakli** [comment]
Sorry about that. Let me try to explain like this:
My server root is W:/www
Laravue works from W:/www/laravue/public/
When I run npm it extracts file to W:/www/laravue/public/js/vendor.js which is correct.
But when I open http://localhost/laravue/public site it shows up empty page because in source it shows: <script src="/js/vendor.js"></script> which corresponds to http://localhost/js/vendor.js which does not exist.

When I try {{ mix('laravue/public/js/vendor.js') }} it says "Unable to locate Mix file".

Again thanks a lot for your help.

**Comment by tuandm** [comment]
@hakankozakli Thanks for the detail. I have never tried working on projects as subfolders, but here are some suggestions:
1. Reconfig laravel mix to use subfolder, i.e `mix.setResourceRoot('/laravue/public/');`, ref: https://github.com/JeffreyWay/laravel-mix/issues/1026. This will fix your current issue, but it still leads to another issue with routers when Laravue requires working as root folder, like: http://your.laravavue.domain/#/dashboard

2. Setup virtual host for your laravue project and point to your `W:/www/laravue/public`, by this way you can access directly to your laravue instance with your custom domain, like: http://laravue.your.local/ - this is the recommendation as it will work extractly the same as live server. It's not too hard to setup virtual host.
