### ISSUE TITLE
API Call not hitting controller

### ISSUE THREAD

**Issue by paragonsoftwaresolutions** [tuandm/laravue#53]
I have created an api route to get a list of items. I have added the route to the routes/api file. I added a method to my api/projects.js file. I then created a method on my index.vue file to get the data. However, it doesn't appear to be hitting my controller method at all. I keep getting this in response, "No query results for model [App\Laravue\Models\Product\Product] manufacturers". I have tested the query that is being used in the method and it returns data. I tried a dd() inside the method and nothing happened. It seems like it isn't hitting the method at all. Below is the code I have used.

index.vue
`async getManufacturers() {
      const { data } = await productResource.manufacturers();
      this.manufacturers = data;
    }`

projects.js
`manufacturers() {
    return request({
      url: '/' + this.uri + '/manufacturers',
      method: 'get',
    });
  }`

api.php
`Route::get('products/manufacturers', 'ProductController@manufacturers');`

ProductController.php
`public function manufacturers()
    {
        dd('Hello');
   }
      `

Am I missing something?

**Comment by tuandm** [comment]
@paragonsoftwaresolutions Thanks for reaching this project. Seems your error is related to Laravel setup. Can I have more information for easy troubleshooting? 
- Can I have full error stacktrace? You can see it in the browser's console or in your logs.
- In the browser's console, what's the URL of API to be called when accessing to the page which causes error? Is it `/api/products/manufacturers`?
- Please double check the current route table by `php artisan route:list` - does it have `products/manufacturers`?

**Comment by paragonsoftwaresolutions** [comment]
Thank you for the super fast response, I'm impressed. I'm sure i'm overlooking something simple, but I just don't see it.

I checked my route table and it does have my route there. Here is screenshot of my route table:
![image](https://user-images.githubusercontent.com/48734537/60993889-5bbcf500-a31d-11e9-9646-5f268f6b4d54.png)

The URL of the api call is /api/products/manufacturers. 
![image](https://user-images.githubusercontent.com/48734537/60994038-a9d1f880-a31d-11e9-95eb-6fac3dfb50f9.png)

Stack Trace from console:

[stacktrace_07-10-2019_14-24-00.txt](https://github.com/tuandm/laravue/files/3378922/stacktrace_07-10-2019_14-24-00.txt)

**Comment by tuandm** [comment]
@paragonsoftwaresolutions 
I don't see any problem in your code. If it returns 404, no error should be logged.
Only one reason I can think is that you forgot to run `compose dump-autoload` (or ProductController wasn't added by artisan) - but it seems impossible. Is this issue resolved?

**Comment by paragonsoftwaresolutions** [comment]
It has not been resolved. I ran dump-autoload. You are correct, I am not getting any errors in my log. The other api calls to api/products work so I'm confused on why this one is not. I do know that if I call this method from products.index it returns data, but that api call is setup differently than this one. Do I need to create a resource for this to work? That seems to be the biggest difference on how these calls differ.

**Comment by tuandm** [comment]
@paragonsoftwaresolutions Sorry I couldn't help you without source code. I tried myself and everything has worked well so far.
1. I created new route in api.php
```
    Route::get('products/manufacturers', function() {
        dd('Hello');
    });
```
It worked: 
![image](https://user-images.githubusercontent.com/490446/61100539-c17dbe00-a490-11e9-9d93-ae5bc314095e.png)

2. I created new ProductController:
```
$ php artisan make:controller ProductController
Controller created successfully.
```
Then created method:
```
    public function manufacturers()
    {
        dd('Hello again');
    }
```
And modified api.php as below
```
    Route::get('products/manufacturers', 'ProductController@manufacturers');
```
It worked again:
![image](https://user-images.githubusercontent.com/490446/61100678-2cc79000-a491-11e9-905f-743763c918a1.png)

I can't think of any reason to make your route unreachable - maybe... typo somewhere?

**Comment by paragonsoftwaresolutions** [comment]
I'm just not sure. I created a new route exactly like the first one you showed and tried to access it directly in the browser and I still get a 404 error. I just don't understand why my route seems to be unaccessible. The route is in my table and I triple checked the spelling just in case. I guess I'll keep researching and see what I come across.

**Comment by paragonsoftwaresolutions** [comment]
Not sure of the reason for this, but I moved my route above my apiResource route and it worked.

**Comment by tuandm** [comment]
@paragonsoftwaresolutions I see. So you have `apiResource` before `products/manufacturers`. It means your app will see `products/manufacturers` as `ProductController@show` which is unavailable or unimplemented. Closing ticket now...
