### ISSUE TITLE
What's the port of the SPA?

### ISSUE THREAD

**Issue by dodoflying** [tuandm/laravue#56]
Hello, after running `npm run watch` on the host machine, what is the url of the front-end?

I tried http://localhost, http://localhost:8000 but not working.

Do you have documentation right now? Thanks!

**Comment by tuandm** [comment]
@dodoflying After running `npm run watch`, you should open another terminal (window or tab) to run `php artisan serve` then open the URL from console.

For the documentation, you can visit the very first version here: https://doc.laravue.dev, we are working on it so it has not been published yet.

**Comment by dodoflying** [comment]
@tuandm, thanks for your reply.

I already started both front-end and back-end. The front-end seems can not start properly. I found port 8000 already is used in the host by VirtualBox. If I open http://localhost:8000, it will display the Laravel project.
```
lsof -i TCP:8000 | grep LISTEN
VBoxHeadl 25478  Don   21u  IPv4 0x16ea6f963d7c228f      0t0  TCP *:irdmi (LISTEN)
```
I know it is not related to your project but I just want to know your suggestion. Thanks!

**Comment by tuandm** [comment]
@dodoflying We don't separate frontend or backend in Laravue - it's still proper Laravel instance. Have you setup Laravel before? Which URL did you use?

**Comment by dodoflying** [comment]
@tuandm Thanks! Now it is working. I'm always thinking there are separated.
