### ISSUE TITLE
Lint error

### ISSUE THREAD

**Issue by Stdubic** [tuandm/laravue#57]
Hello,

can you help plz?

npm run lint -- --fix
npm ERR! missing script: lint

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/stevanaleksic/.npm/_logs/2019-07-31T10_16_47_164Z-debug.log

**Comment by tuandm** [comment]
@Stdubic `lint` option is not ready for the master branch, please wait a few days to get updated, or switch to [feature/documentation](https://github.com/tuandm/laravue/tree/feature/documentation) branch. Sorry for this convenience, the document has not been officially published yet.

**Comment by Stdubic** [comment]
Thanks,

Great work !!!
