### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by speedtechj** [tuandm/laravue#60]
ENOENT: no such file or directory, open '/Users/newowner/laravue/node_modules/.staging/@types/jquery-fc08fbbe/JQueryStatic.d.ts'
npm ERR! Error while executing:

**Comment by tuandm** [comment]
@speedtechj Can you please post the full error log here? I can't not reproduce this issue.

**Comment by MarcTG** [comment]
I got the same problem, I will post below the full error log

**Comment by MarcTG** [comment]
18515 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
18516 warn enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/home/maxtor/Sites/laravue/node_modules/.staging/fsevents-31abf324/node_modules/abbrev' -> '/home/maxtor/Sites/laravue/node_modules/.staging/abbrev-c35c9dcb'
18517 verbose enoent SKIPPING OPTIONAL DEPENDENCY: This is related to npm not being able to find a file.
18517 verbose enoent SKIPPING OPTIONAL DEPENDENCY:
18518 verbose stack TypeError: err.code.match is not a function
18518 verbose stack     at BB.try.catch.err (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/with-tarball-stream.js:110:55)
18518 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
18518 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
18518 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
18518 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
18518 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:690:18)
18518 verbose stack     at _drainQueueStep (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
18518 verbose stack     at _drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:131:9)
18518 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:147:5)
18518 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
18518 verbose stack     at runCallback (timers.js:794:20)
18518 verbose stack     at tryOnImmediate (timers.js:752:5)
18518 verbose stack     at processImmediate [as _immediateCallback] (timers.js:729:5)
18519 verbose cwd /home/maxtor/Sites/laravue
18520 verbose Linux 5.0.0-23-generic
18521 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install"
18522 verbose node v8.10.0
18523 verbose npm  v6.9.0
18524 error err.code.match is not a function
18525 verbose exit [ 1, true ]
