### ISSUE TITLE
vendor.js is huge even after npm run prod

### ISSUE THREAD

**Issue by SibaAl** [tuandm/laravue#62]

**Comment by SibaAl** [comment]
Fresh install - no edits at all
vendor.js is 27Mb even after running in production mode.

**Comment by tuandm** [comment]
Hi @SibaAl, 
After compression, app.js is only 552KB, vendor.js is 1.4M and this will be cached by the browser. You can check on laravue.dev.

Alternatively, you can apply lazyloading for Vue components with Laravel Mix and webpack.

**Comment by SibaAl** [comment]
Hi @tuandm ,
Thank you for your reply, I did check laravue.dev file sizes are as you mentioned, can you think of anything to cause such large files seizes? I cloned your repo without doing any changes!

**Comment by tuandm** [comment]
@SibaAl Because in your local, those files are not minified and compressed. You can run `npm run report` to see the sizes of each library in the bundle file.

**Comment by tuandm** [comment]
@SibaAl I see your question on [StackOverFlow](https://stackoverflow.com/questions/57364325/vendor-js-is-huge-after-npm-run-production) and happy to know your issue was fixed. Closing this issue.
