### ISSUE TITLE
whiteList no auth routes does not support Dynamic Route Matching

### ISSUE THREAD

**Issue by Ahmed-Aboud** [tuandm/laravue#67]
the whiteList constant in permission.js does not support vue-router Dynamic Route Matching and redirect password-reset/:token  to  /login
here are permission.js and router/index.js
![whitelist1](https://user-images.githubusercontent.com/25877831/63432535-a2743380-c421-11e9-812a-582ce75ed36a.jpg)
![whitelist2](https://user-images.githubusercontent.com/25877831/63432536-a2743380-c421-11e9-9526-de8e45b60a62.jpg)

**Comment by tuandm** [comment]
@Ahmed-Aboud Whitelist is supposed to contain static routes like login or error pages, dynamic routes with params are not supported. You have to modify the condition yourself, for example:
```
    if (whiteList.indexOf(to.path) !== -1) {
      // in the free login whitelist, go directly
      next();
    } else if (to.path.match('/reset-password/')) {
      next();
    } else {
      // other pages that do not have permission to access are redirected to the login page.
      next(`/login?redirect=${to.path}`);
      NProgress.done();
    }
```
Or you can write a method to replace `String.prototype.indexOf`

**Comment by tuandm** [comment]
@Ahmed-Aboud I just tried your code but seems it doesn't work. Can you please add sample whitelist route to your PR so I can test directly?

**Comment by Ahmed-Aboud** [comment]
here is my router/index.js
```
    path: '/reset-password/:token',
    component: () => import('@/views/reset-password/index'),
    hidden: true
  },
```
and here is my permissions.js
`const whiteList = ['/login', '/auth-redirect', '/forgot-password', '/reset-password/:token'];`
`if (whiteList.indexOf(to.matched[0] ? to.matched[0].path : '') !== -1) {`
