### ISSUE TITLE
你这是直接照抄vue-element-admin啊？

### ISSUE THREAD

**Issue by nikolausliu** [tuandm/laravue#68]
[vue-element-admin](https://github.com/PanJiaChen/vue-element-admin)，你这富文本编辑器的文档都和他一样，抄袭好歹改一改？

**Comment by tuandm** [comment]
@nikolausliu I discussed with @PanJiaChen and he agreed for me to start the documentation based on his work. Therefore some text may be the same, but you can see I have modified the original one with my investigation and new code.

**Comment by nikolausliu** [comment]
okay. i apologize for my excessive words

**Comment by tuandm** [comment]
@nikolausliu Thanks, you are welcome!
