### ISSUE TITLE
Laravel 6.0 LTS support

### ISSUE THREAD

**Issue by fetova** [tuandm/laravue#72]
Hi!

First, thanks a lot, is a great work you did here. I'm still doing some things to adapt to my needs but that is another matter.

Laravel 6.0 is out, and i would like to do things on that version, there is a near plan to support it?

Thanks!

**Comment by tuandm** [comment]
@fetova Thanks for the notice. We already have plan to support Laravel 6.0 but it will require lots of work since 6.0 changes UI components. We will start working on this soon.

**Comment by fetova** [comment]
I see. I checked just jwt will give troubles as doesn't seems too active, You might want to drop it as one aspect of the work I fear...

Thanks a lot! I will be keeping an eye on this :grin:

**Comment by jameskaf** [comment]
jwt still highly in use, not sure that would be a good idea to drop it

**Comment by fetova** [comment]
@jameskaf I said that because of this (1) but, just in case, i'm new on this library. I have no elements to choose one thing or other.

Also, saw this other one (2) , that's why i said the things before.

(1) https://github.com/tymondesigns/jwt-auth/issues/1860#issuecomment-527859326
(2) https://github.com/tuandm/laravue/issues/54#issuecomment-511221609

**Comment by soundar8562** [comment]
Even better if you plan to Passport instead of JWT

**Comment by tuandm** [comment]
#77
