### ISSUE TITLE
Usiny Element UI Icons in Sidenav

### ISSUE THREAD

**Issue by martyh888** [tuandm/laravue#73]
I can not get any Elelemt UI icons working in the side navigation

meta: { title: 'Import', icon: 'el-icon-upload', noCache: true },

This doesn't who the upload icon. if I use the standard icons this works fine is there documentation to how I declare these el-icons inside a meta grouping?

**Comment by tuandm** [comment]
@martyh888 Thanks for reporting this issue. Currently the sidebar only supports svg icons, we will add Element icons soon.
