### ISSUE TITLE
New constantRoute always redirect to login page.

### ISSUE THREAD

**Issue by paulohlimamaia** [tuandm/laravue#76]
I do not know what i'm doing wrong, it may be something small that i do not noticed but i can't figure it out.

This is my route in the **constantRoutes** on **routes/index.js**.
The new contstant route i'm trying to add is the forgot page. (A simple page to a Forgot my password kind of page).

**`
{
    path: '/forgot',
    component: () => import('@/views/forgot/index'),
    hidden: true,
  },
`**

When i do a **`this.$router.push('/forgot');`** or a **`this.$router.replace('/forgot');`** from the login page, it always redirect to that same login page but with redirect to the new Forgot page i'm creating and then, when i do the login, it redirects me to the forgot page i'm creating.

It wort metioning that the same occurs with the **404** and **401** routes that already came with the project and are in the same constantRoutes as my new created forgot page.

**Comment by azizramdan** [comment]
I think this same problem with https://github.com/tuandm/laravue/issues/51

**Comment by paulohlimamaia** [comment]
@azizramdan 

I searched the whole docs for this guideline but can't find it.
The strange thing is that in the **asyncRoutes** i can create pages with no problems, but the **constantRoutes** i can't. I know for sure it's some small thing i'm doing wrong but I can't figure it out.

**Comment by tuandm** [comment]
@paulohlimamaia You have to add your `/forgot` router to the whitelist which is defined in `js/permission.js`:
```
const whiteList = ['/login', '/auth-redirect']; // no redirect whitelist
```

**Comment by paulohlimamaia** [comment]
@tuandm thank you, this solved the issue. 

Pardon me if this was in the documentation but i couldn't find it anywhere there.

**Comment by tuandm** [comment]
@paulohlimamaia Sorry, actually it's not mentioned in the documentation. I will update it then :). Thank you.
