### ISSUE TITLE
Laravue project in subfolder?

### ISSUE THREAD

**Issue by caraffa** [tuandm/laravue#79]
Hi, @tuandm.
First off: thanks from heart for this great work. It looks very promising.
I'm planning to integrate your framework in existing projects so it would be vital for me to have the possibility of serving a laravue project from a subfolder (e.g.: https://my.own.dev/laravue-project1 along with https://my.own.dev/laravue-project2).
While browsing for related info, I found this: https://dev.to/iqbaltld/comment/ao2d
As I can see, at the moment, there's no possibility for running a Laravue project other then to have it in the main root folder/domain.
This is obviously more of a feature request than a bug. Do you have plans about that? Are there at the moment any work-arounds? I'm sure that many other people would be interested in such an improvement.

Thanks again for this great piece of work

**Comment by tuandm** [comment]
@caraffa Thanks for reaching out to this project. I will create a document for request and get back to you soon :).

**Comment by tuandm** [comment]
#81

**Comment by tuandm** [comment]
@caraffa https://doc.laravue.dev/guide/#change-the-path

**Comment by caraffa** [comment]
Great!

**Comment by caraffa** [comment]
@tuandm Hi, Tuan Dong.
I've played a bit with this new enhancement and it is working, it's very good! Yet, I cannot consider it a project I can integrate _seamlessly_ in other, let's say, _generic_ projects.
I'll explain my point with an example.
Following your step-by-step guides I can successfully start a laravue or laravue-core project and access it by means of the built-in http server. 
After running `php artisan serve`, I can effectively access my project at address 127.0.0.1:8000 like this: `http://127.0.0.1:8000/LaravueTest` (or `http://127.0.0.1:8000/LaravueCoreTest`) and I can successfully log into the dashboard. It is working fine.
But, as clearly stated in the documentation, the built-in http server is meant _only for development purposes_, lacking thus the features of a full fledged http server (like Apache or Nginx).
Furthermore, in a real world scenario I cannot consider deploying my app to a dev-only http server.
Let's consider, as an example, the following "real world" scenario: let's imagine we've a Wordpress site with its own admin pages, blogs, articles, etc. and let's imagine also that we'd like to add some special functionality to our site by means of your framework.
The ideal situation would be like this: hitting `https://www.myownwordpresssite.eu/` would grant the visitor generic access to our blog, e-commerce or whatsoever it be, but by hitting (or may be by redirecting trough some internal link to) `https://www.myownwordpresssite.eu/LaravueReservedArea`, the visitor would be granted access to his own reserved area.
Right now I can't see a way of implementing that. I've found lots of tutorials about how to deploy a pure laravel project to production, to a real hosted server (thus even eliminating 'public' from the url), but none seem to fit what I'm trying to achieve.
In any case, I thank you once again for your work.

P.S. by  the way, I've discovered a typo in your doc page [https://doc.laravue.dev/guide/#getting-started](https://doc.laravue.dev/guide/#getting-started). If you hit the "laravue-core" link, you're redirected to `https://github.com/tuandm/laravel-core`, which is clearly a non-existent project. It should be `https://github.com/tuandm/laravue-core`. (_laravue_ instead of _laravel_)

**Comment by caraffa** [comment]
@tuandm 
Ok, Tuan Dong, I understand and share all of your points. 
I'm fully aware that each real-world project needs its good deal of customizations. And I know also how to setup a system (e.g. localhost) which is fully equivalent to `php artisan serve`.
But my aim is to integrate your framework into an existing project (e.g. a wordpress blog located at document root).
I've been digging into your code for a while and I think I've found how to change a client side request so that it points to, for example, `http://localhost/ReservedArea/api/auth/login`. It can be done by modifying the MIX_BASE_API env variable.
What I don't seem to be able to find is a way to make the underlying Laravel PHP Layer, answer such request (yes, sorry, I'm new to Laravel). 
I'd love to change the code in such a way that you can integrate the changes as a PR into your project.
I've noticed, indeed, that the BASE_API env var is not used at all in the entire project, besides for constructing the MIX_BASE_API var.
I think that the use of an env var in the PHP api layer would do the trick. Could you give me some hint about that? Which are the php files where the api is exposed?
P.S. Actually I'm experimenting with laravue-core, not laravue. But I'm confident that If i can find a way to do what I've in my head, it can be brought seamlessly into the "main" laravue" project.

**Comment by tuandm** [comment]
@caraffa 
Thanks for your email. Integrating Laravue into Wordpress doesn't seem to be suitable because Wordpress APIs aren't too enough as for me. Besides, by integrating Laravue, we abandon the WP's admin dashboard which is still good and feasible (except it's slow). However, integrating Laravue to other systems which provide full APIs is not too hard, and sounds attractive.

> I've noticed, indeed, that the BASE_API env var is not used at all in the entire project, besides for constructing the MIX_BASE_API var.
Indeed, you can remove that BASE_API and use MIX_BASE_API directly.

> I think that the use of an env var in the PHP api layer would do the trick. Could you give me some hint about that? Which are the php files where the api is exposed?
Sorry I don't get this point, can you please explain a bit more?

**Comment by caraffa** [comment]
> > I think that the use of an env var in the PHP api layer would do the trick. Could you give me some hint about that? Which are the php files where the api is exposed?
> 
> 
> Sorry I don't get this point, can you please explain a bit more?

Well, I've been doing some search on the web, and I'm realizing now that I was (wrongly) assuming that Laravel has the same flexibility of Wordpress when it comes to such stuff.
From this perspective, Wordpress is quite flexible when it comes to "self-containment", so to speak.
I can have a Wordpress "root" install in my document-root, for example, along with an arbitrary number of other Wordpress installs, each one neatly fit in its own subfolder and, most important, _fully independent_ from each other. What is interesting is that Wordpress doesn't require any particular VHost configuration in the server. It handles everything at .htaccess level in its own directory, which is also configured almost automatically at setup time.
So a situation like the following is children play with Wordpress:

- An e-commerce in the root folder (accessed via https://localhost)
- A reserved area for the e-commerce customers in the ReservedArea subfolder (accessible via https://localhost/ReservedArea)
- A (public) Blog in its own PublicBlog subfolder (accessible via https://localhost/PublicBlog)
- A (private) Blog in its own PrivateBlog subfolder (accessible via https://localhost/PrivateBlog)

With each item being a _fully independent_ wordpress install. (Obviously such stuff can be implemented in a lot of different ways, even more efficient than that, but this is just an example)

Here I was (wrongly) assuming that the same was valid for Laravel projects, but I'm seeing (by looking at the big number of questions tagged as "Laravel project in subfolder" on Stackoverflow.com, for example) that things don't go that easy.
In particular, I'd rather avoid messing with the VHost configurations, since not all web hosting providers give you such low level access to their servers' configs.
That's why I was looking for a "wordpress-like" solution. I was looking for modifications to the laravel structure so that it would fit into what I'm trying to achieve. That's it
Ok, enough for now. I'll dig deeper into the Laravel source code. 
Again thanks a lot for your support.

**Comment by caraffa** [comment]
@tuandm 
I got it!!! I've found the solution! :-D
I can have my laravue-core installed in a subfolder of the document root (e.g: `/Library/WebServer/Documents/ReservedArea` where `/Library/WebServer/Documents` is my apache 2.4 document root) and access the project like this: `http://localhost/ReserverdArea/public`.
From there I'm able now to succesfully log into the dashboard! No 404 error!
Basically, I've changed the .env and the RouteServiceProvider.php files to something like this:
```
...

BASE_API=/api

LARAVUE_PATH=LaravueCoreTest/public/

MIX_BASE_API="/${LARAVUE_PATH}${BASE_API}"
MIX_LARAVUE_PATH="${LARAVUE_PATH}"
```

```
    /**
     * Define the "api" routes for the application.
     *
     * These routes are typically stateless.
     *
     * @return void
     */
    protected function mapApiRoutes()
    {
        Route::prefix(env('LARAVUE_PATH') . 'api')
             ->middleware('api')
             ->namespace($this->namespace)
             ->group(base_path('routes/api.php'));
    }

```


If you agree, I'll move the whole discussion to your laravue-core project and from there I'll open a PR.
