### ISSUE TITLE
Files are not being found / Blank page

### ISSUE THREAD

**Issue by andrevenlibretrend** [tuandm/laravue#82]
Hello everyone,

So I've just followed the steps to create a new project over https://doc.laravue.dev/guide/#getting-started and my page is fully blank, the files are not being found.

![image](https://user-images.githubusercontent.com/46103291/66837926-b6d53800-ef5b-11e9-85fe-ed7ef94cb7f4.png)

I am using the command ```docker-compose up``` to start a local server that runs the database server, the php server and nginx, may this have something to do with the problems I am having?

Appreciate the help.

**Comment by tuandm** [comment]
@andrevenlibretrend 
Did you run `yarn install`?
How is the result of `yarn run dev/watch`? 

We haven't provided docker for this project yet. The `Dockerfile` is used for Gitlab CI.

**Comment by andrevenlibretrend** [comment]
@tuandm 
I have ran ```yarn install``` indeed
```yarn run dev/watch``` outputs ```Compiled successfully in Xms```

So you wouldn't recommend me using Docker yet?

**Comment by tuandm** [comment]
@andrevenlibretrend Yes, you should not use docker. Please setup your webserver (nginx/apache) or simply run `php artisan serve`. Hope it helps.

**Comment by andrevenlibretrend** [comment]
Alright thank you for your help @tuandm , much appreciated

**Comment by onos9** [comment]
Hello guys

I think am also facing this issue, after following the installation procedure and run `php artisan serve` then visit the URL: http://127.0.0.1:8000
I get a blank page instead of the the login form, please help
![Screenshot](https://user-images.githubusercontent.com/16125607/67004159-8c0fee80-f0d7-11e9-8141-f7caee4ced1f.png)

**Comment by tuandm** [comment]
@onos9 Can you please check the browser's console to see any error there?

**Comment by onos9** [comment]
@tuandm thank you so much for the quick reply, but have gotten it sorted out by running `php yarn run dev` I have actually omitted that command, my bad thanks.
