### ISSUE TITLE
Console warning

### ISSUE THREAD

**Issue by leonpug** [tuandm/laravue#86]
Hi,
great Job, tuandm!

I following the guide: https://doc.laravue.dev/guide/development/work-with-resource.html to create new route on menu and view (I create model, resource, controller, view, etc following the guide exactly).
All seems be ok, only a couple of warning on console (for every new route):
[vue-i18n] Value of key 'route.Journal' is not a string!
[vue-i18n] Cannot translate the value of keypath 'route.Journal'. Use the value of keypath as default.
...
This is my router module:
import Layout from '@/layout';
const journalRoutes = {
  path: '/journal',
  component: Layout,
  redirect: 'noredirect',
  name: 'Journal',
  meta: {
    title: 'Journal',
    icon: 'education',
    permissions: ['view menu journal'],
  },
  children: [
    { path: 'source',
      component: () => import('@/views/journal/Source'),
      name: 'Source',
      meta: { title: 'Source', icon: 'dollar' },
    },
    {path: 'code',
      component: () => import('@/views/journal/Code'),
      name: 'Code',
      meta: { title: 'Code', icon: 'password' },
    }, ],};
export default journalRoutes;

I can translate the routes? How?

**Comment by tuandm** [comment]
@leonpug You can check this document: https://doc.laravue.dev/guide/development/new-page.html#i18n

**Comment by leonpug** [comment]
thanks for response.
how can I force app lang without using lang selector?
I set lang in config/app.php, it's enough?

**Comment by tuandm** [comment]
@leonpug i18n is integrated by default on Laravue. Removing it requires extra development and is not in our plan at this moment. Maybe we will implement a setting to make this feature more flexible.

For the quick solution, you can go to https://github.com/tuandm/laravue/blob/master/resources/js/lang/index.js, line 53 - change to language you want to use. Then you should remove LangSelect related code.
```
const i18n = new VueI18n({
  ...
  locale: getLanguage(), // Change to 'en' for example
  ...
});
```

**Comment by leonpug** [comment]
ok, thanks

**Comment by leonpug** [comment]
Hi tuandm,
I need an advice: I try to use localization to format date and currency following guides:
https://kazupon.github.io/vue-i18n/guide/datetime.html
https://kazupon.github.io/vue-i18n/guide/number.html
It works, but not for formatted input...
Any help?
thanks

**Comment by leonpug** [comment]
Hi tuandm,

for numbers localization in table view, this code it's working for me:
```
...
<el-table-column width="100" label="In">
  <template slot-scope="scope">
    <span>{{ $n(scope.row.cash, 'currency') }}</span>
  </template>
</el-table-column>
...
```
(cash is decimal(10,2) data type)
with this code in js/lang/index.js:
```
const numberFormats = {
  it: {
    currency: {
      style: 'currency', currency: 'EUR',
    },
  },
};
```
instead for date localization I use your parseTime utils, because the datetime localization it's not working.
With this code:
`$d(scope.row.date, 'short')`
and
```
const dateTimeFormats = {
  it: {
    short: {
      day: 'numeric', month: 'numeric', year: 'numeric',
    },
  },
};
```
I get an error:
`RangeError: date value is not finite in DateTimeFormat.format()`

To formatting (or localizing) input date and numbers I have no idea...
(I'm looking for a general solution to format data from and to db)
sorry for my bad english

**Comment by tuandm** [comment]
@leonpug Sorry for this very late response. I hope you already had solution for this issue. Some comments:
- `parseTime` return customized string which is not suitable to use to create DateTime object
- I would go with server side solution (which returns formated data for datetime/currency).
 
Happy coding.
