### ISSUE TITLE
Yarn install error : jsonlint > nomnom@1.8.1: Package no longer supported.

### ISSUE THREAD

**Issue by phobrv** [tuandm/laravue#89]
I have this error when run: yarn install
- Yarn : 1.19.1
- Node: 12.5
- Win 10
![yarn_error](https://user-images.githubusercontent.com/9550597/68034924-35b8c780-fcf5-11e9-883e-a365527d747d.png)

**Comment by tuandm** [comment]
@phobrv Is `git` command ready on your computer?

**Comment by phobrv** [comment]
yes.

**Comment by tuandm** [comment]
@phobrv 
Seems your network has problem (github.com is unaccessible or port 9418 is not opened), which is not related to Laravue setup.
From your error log, this command is unable to execute:
```
git ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
```
Please help to check.

**Comment by phobrv** [comment]
@tuandm 
I had run and result

D:\laragon\www\laravue
λ git  ls-remote --tags --heads git://github.com/adobe-webplatform/eve.git
fatal: unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )

**Comment by tuandm** [comment]
@phobrv 
Sorry for the late response.
As I said above, this issue seems not related to Laravue. You have to fix yourself.

Your computer somehow can not access to github.com:9418. Please try to investigate.

Regards.

**Comment by lalitj** [comment]
@phobrv @tuandm I am seeing the same issue. Let us know here if you found the solution.
![download](https://user-images.githubusercontent.com/990271/68542819-501a3180-03d6-11ea-9dca-c1ebc41f82ce.png)

**Comment by lalitj** [comment]
@phobrv @tuandm Actually nomnom package is deprecated now.
https://www.npmjs.com/package/nomnom
![Screenshot_3](https://user-images.githubusercontent.com/990271/68543002-c0758280-03d7-11ea-9b33-c9898efec5f9.png)

**Comment by tuandm** [comment]
@lalitj Your issue seems related to yarn cache, please clear the cache, remove node_modules folder and install again.
For the nomnom package, it's just a warning and should not affect the laravue app. I will check.

Thanks.

**Comment by shanyul** [comment]
@phobrv I got this problem and i fixed by run ‘git config --global url."https://".insteadOf git://’ in the project root path.
