### ISSUE TITLE
How to update the project

### ISSUE THREAD

**Issue by 136187101** [tuandm/laravue#92]
Hello, I used laravue to combine my code, how to update to the latest version of laravue? I am a newbie. Sorry.

**Comment by tuandm** [comment]
@136187101 
Laravue is positioned for starting projects from scratch and it doesn't support update at this moment. You have to pick the latest version and start developing your projects from there. 

Another approach is forking this repo to yours, then you can get updates from the main repo and merge to your one - this solution may create conflicting if you add lots of changes on your repo.

**Comment by 136187101** [comment]
I am very glad that you can answer my question, thank you.

> @ 136187101
> Laravue可以从头开始项目，目前不支持更新。您必须选择最新版本，然后从那里开始开发项目。
> 
> 另一种方法是将该存储库分派给您的存储库，然后您可以从主存储库获取更新并合并到您的存储库中-如果您在存储库上添加大量更改，则此解决方案可能会产生冲突。

I am very glad that you can answer my question, thank you.
