### ISSUE TITLE
what is the best practice  to add signup and connect this system with website.?

### ISSUE THREAD

**Issue by omaralwi** [tuandm/laravue#96]
I used this for logistics sytem , it very helpful , but I need to connect it with website , and add signup to become one system for visitors and admins & managers.

**Comment by djar00** [comment]
Hi
I did something like that in my project and it works really cool.
What is your specific problem?

**Comment by omaralwi** [comment]
thank you for a reply,, i need idea about how to make a website with a system and signup process, any problem will happen.?!

**Comment by tuandm** [comment]
Laravue is positioned for backend solution where users will be [managed](https://laravue.dev/#/administrator/users), so registration is not on our demo/plan. To do so, there are 2 suitable options
1. Serve backend in [subfolder](https://doc.laravue.dev/guide/#change-the-path) such as /admin... then create a frontend page to register user normally. 
2. Create a registration form via Laravue package (like login page) but add route to the whitelist. You can check this issue: https://github.com/tuandm/laravue/issues/67. You can also check example code on [User listing](https://github.com/tuandm/laravue/blob/master/resources/js/views/users/List.vue) to see how to send an API for creating user.

Regards.

**Comment by omaralwi** [comment]
thank you this is useful ,, I will Try with your tutorials.
