### ISSUE TITLE
how to Add reset password and Email Verification.?

### ISSUE THREAD

**Issue by omaralwi** [tuandm/laravue#99]
I was added Register Successfully But I can not add Email Verification and reset password with JWT in front End,  and How To prevent user from browse any page or route untill he make Email Verification in vuejs.?
Or make guest signup untill Verificate Email Then become verified User .?
Please any idea about this.?

**Comment by tuandm** [comment]
@omaralwi You need to prevent non-authorized users from logging in to the system by changing this login method: https://github.com/tuandm/laravue/blob/master/app/Http/Controllers/AuthController.php, or extend Auth::guard() to custom authentication (with verified email checked).

Email Verification and Reset Password should be done in Laravel part (with PHP).

**Comment by omaralwi** [comment]
thank you I will try your tutorials.

**Comment by khayyak** [comment]
who has the same problem , can follow steps in this tutorial  : https://codebriefly.com/vue-js-reset-password-laravel-api/#comment-1067
